import { text, timestamp, uuid } from "drizzle-orm/pg-core";
import { createTable } from "../../../utils/create-table.js";
import { extractTypeEnum } from "../shared/enums.js";

export const allergiesRaw = createTable("raw.allergies", {
  // Source columns as text (all fields from Allergies extract)
  allergyId: text("allergy_id"),
  appointmentId: text("appointment_id"),
  allergyTypeId: text("allergy_type_id"),
  allergyType: text("allergy_type"),
  onsetDate: text("onset_date"),
  deactivationReason: text("deactivation_reason"),
  medicineId: text("medicine_id"),
  medicine: text("medicine"),
  reactionId: text("reaction_id"),
  reactions: text("reactions"),
  reactionTypeId: text("reaction_type_id"),
  reactionType: text("reaction_type"),
  severityId: text("severity_id"),
  severity: text("severity"),
  reactionNotes: text("reaction_notes"),
  isActive: text("is_active"),
  isDeleted: text("is_deleted"),
  insertedById: text("inserted_by_id"),
  insertedBy: text("inserted_by"),
  updatedById: text("updated_by_id"),
  updatedBy: text("updated_by"),
  insertedAt: text("inserted_at"),
  updatedAt: text("updated_at"),
  patientId: text("patient_id"),
  patient: text("patient"),
  isConfidential: text("is_confidential"),
  practiceId: text("practice_id"),
  practice: text("practice"),
  mgencode: text("mgencode"),
  mclacode: text("mclacode"),
  medTechId: text("med_tech_id"),
  medicineClassificationId: text("medicine_classification_id"),
  allergyCategoryId: text("allergy_category_id"),
  allergyCategory: text("allergy_category"),
  comment: text("comment"),
  substanceTypeId: text("substance_type_id"),
  substanceType: text("substance_type"),
  favouriteSubstanceId: text("favourite_substance_id"),
  favouriteSubstance: text("favourite_substance"),
  diseaseId: text("disease_id"),
  disease: text("disease"),
  otherSubstance: text("other_substance"),
  medicineTypeId: text("medicine_type_id"),
  medicineType: text("medicine_type"),
  userLoggingId: text("user_logging_id"),
  loggingUserName: text("logging_user_name"),
  showOnPortal: text("show_on_portal"),
  warningType: text("warning_type"),
  rowinactive: text("rowinactive"),
  isReviewed: text("is_reviewed"),
  providerId: text("provider_id"),
  provider: text("provider"),
  practiceLocationId: text("practice_location_id"),
  locationName: text("location_name"),
  perOrgId: text("per_org_id"),
  loadedDateTime: text("loaded_date_time"),

  // Lineage columns
  s3Bucket: text("s3_bucket").notNull(),
  s3Key: text("s3_key").notNull(),
  s3VersionId: text("s3_version_id").notNull(),
  fileHash: text("file_hash").notNull(),
  dateExtracted: text("date_extracted").notNull(),
  extractType: extractTypeEnum("extract_type").notNull(),
  loadRunId: uuid("load_run_id").notNull(),
  loadTs: timestamp("load_ts", { withTimezone: true }).notNull().defaultNow(),
});
