CREATE SCHEMA "core";
--> statement-breakpoint
CREATE SCHEMA "etl";
--> statement-breakpoint
CREATE SCHEMA "raw";
--> statement-breakpoint
CREATE SCHEMA "stg";
--> statement-breakpoint
CREATE TYPE "public"."appointment_status" AS ENUM('scheduled', 'confirmed', 'arrived', 'in_progress', 'completed', 'cancelled', 'no_show', 'rescheduled');--> statement-breakpoint
CREATE TYPE "public"."extract_type" AS ENUM('Patient', 'Appointments', 'Immunisation', 'Invoices', 'InvoiceDetail', 'Provider', 'PracticeInfo', 'Measurements', 'Diagnosis', 'Recalls', 'Inbox', 'InboxDetail', 'Medicine', 'NextOfKin', 'Vaccine', 'Allergies', 'AppointmentMedications', 'PatientAlerts');--> statement-breakpoint
CREATE TYPE "public"."immunisation_status" AS ENUM('completed', 'pending', 'overdue', 'cancelled', 'not_required');--> statement-breakpoint
CREATE TYPE "public"."status_group" AS ENUM('active', 'completed', 'cancelled', 'no_show');--> statement-breakpoint
CREATE TABLE "raw"."patients" (
	"patient_id" text,
	"nhi_number" text,
	"is_nhi_validate" text,
	"title" text,
	"first_name" text,
	"middle_name" text,
	"family_name" text,
	"full_name" text,
	"preferred_name" text,
	"other_maiden_name" text,
	"marital_status_id" text,
	"marital_status" text,
	"gender_id" text,
	"gender" text,
	"dob" text,
	"age" text,
	"age_type" text,
	"age_group" text,
	"is_alive" text,
	"death_date" text,
	"dob_source" text,
	"picture_path" text,
	"consented_to_share" text,
	"place_of_birth" text,
	"country_of_birth_id" text,
	"country_of_birth" text,
	"cell_number" text,
	"day_phone" text,
	"night_phone" text,
	"email" text,
	"secondary_email" text,
	"preferred_contact_method" text,
	"consent_text_messaging" text,
	"is_portal_user" text,
	"is_active" text,
	"is_deleted" text,
	"inserted_by" text,
	"updated_by" text,
	"inserted_at" text,
	"updated_at" text,
	"notes" text,
	"is_gender_self_identified" text,
	"sex_related_gender" text,
	"is_worked_visa_required" text,
	"balance" text,
	"med_tech_balance" text,
	"med_tech_date_last_pay" text,
	"med_tech_date_last_stmt" text,
	"register_status_id" text,
	"register_status" text,
	"med_tech_nok" text,
	"practice_name" text,
	"calculated_balance" text,
	"last_statement_date" text,
	"last_invoice_date" text,
	"last_payment_date" text,
	"provider_name" text,
	"chart_number" text,
	"extention" text,
	"practice_remarks" text,
	"is_insured" text,
	"insured_remarks" text,
	"smoking_type" text,
	"account_holder" text,
	"account_holder_employer" text,
	"is_community_service_card" text,
	"community_service_card_no" text,
	"community_service_card_exipry_date" text,
	"community_service_card_sighted" text,
	"is_health_card" text,
	"health_card_no" text,
	"health_card_expiry_date" text,
	"health_card_sighted" text,
	"winz" text,
	"is_transfer_of_records" text,
	"transfer_of_records_remarks" text,
	"enrolment_type" text,
	"enrolment_status_id" text,
	"enrolment_status" text,
	"enrolment_date" text,
	"enrolment_method" text,
	"enrolment_verifier" text,
	"funding_status_id" text,
	"funding_status" text,
	"rejection_reason" text,
	"funding_from" text,
	"funding_to" text,
	"account_group" text,
	"gms_code" text,
	"residential_status" text,
	"is_nka" text,
	"is_high_care" text,
	"high_care_reason" text,
	"is_care_plan" text,
	"is_new_registeration" text,
	"is_opt_off" text,
	"is_bp_graph" text,
	"is_bmi_graph" text,
	"is_inr_graph" text,
	"is_hba1c_graph" text,
	"asr_mark_status" text,
	"is_height_graph" text,
	"is_weight_graph" text,
	"is_hc_graph" text,
	"nes_status" text,
	"nes_comments" text,
	"med_tech_balance_date" text,
	"is_heart_rate" text,
	"is_premature" text,
	"premature_week" text,
	"patient_pho_id" text,
	"consult_updated_at" text,
	"occupation" text,
	"emergency_contact" text,
	"emergency_contact_name" text,
	"secondary_contact" text,
	"secondary_contact_name" text,
	"provider_id" text,
	"practice_id" text,
	"portal_registration_status" text,
	"registration_date" text,
	"med_tech_id" text,
	"permanent_address_house_number" text,
	"permanent_address_building_number" text,
	"permanent_address_street_number" text,
	"permanent_address_suburb_town_id" text,
	"permanent_address_suburb" text,
	"permanent_address_city_area_id" text,
	"permanent_address_city" text,
	"permanent_address_postal_code" text,
	"permanent_address_latitude" text,
	"permanent_address_longitude" text,
	"permanent_address_country_id" text,
	"permanent_address_country" text,
	"permanent_address" text,
	"permanent_address_dhb_code" text,
	"permanent_address_domicile_code" text,
	"permanent_address_deprivation_quintile" text,
	"permanent_address_deprivation_decile" text,
	"permanent_address_meshblock" text,
	"permanent_address_match_score" text,
	"permanent_address_uncertainty_code" text,
	"temporary_address" text,
	"postal_address_house_number" text,
	"postal_address_building_number" text,
	"postal_address_street_number" text,
	"postal_address_suburb_town_id" text,
	"postal_address_suburb" text,
	"postal_address_city_area_id" text,
	"postal_address_city" text,
	"postal_address_postal_code" text,
	"postal_address_latitude" text,
	"postal_address_longitude" text,
	"postal_address_country_id" text,
	"postal_address_country" text,
	"postal_address" text,
	"postal_address_dhb_code" text,
	"postal_address_domicile_code" text,
	"postal_address_deprivation_quintile" text,
	"postal_address_deprivation_decile" text,
	"postal_address_meshblock" text,
	"postal_address_match_score" text,
	"postal_address_uncertainty_code" text,
	"ethnicity_id" text,
	"ethnicity" text,
	"ethcode" text,
	"ethcode2" text,
	"secondary_ethnicity_id" text,
	"secondary_ethnicity" text,
	"ethcode3" text,
	"other_ethnicity_id" text,
	"other_ethnicity" text,
	"enrolment_id" text,
	"pho_name" text,
	"enrolment_expiry_date" text,
	"is_consent_to_share" text,
	"is_work_visa" text,
	"work_visa_start_date" text,
	"work_visa_expiry_date" text,
	"enrolment_quarter" text,
	"practice_location" text,
	"account_holder_type_id" text,
	"patient_type" text,
	"breast_screen_id" text,
	"breast_screen" text,
	"is_pregnant" text,
	"apply_charges" text,
	"include_in_print" text,
	"is_careplus" text,
	"care_plus_start_date" text,
	"care_plus_enddate" text,
	"care_plus_linc_status_id" text,
	"care_plus_linc_status" text,
	"nhi_status_id" text,
	"nhi_status" text,
	"per_org_id" text,
	"loaded_date_time" text,
	"account_holder_profile_id" text,
	"comunity_service_effective_date" text,
	"default_gpmc_no" text,
	"default_gp_name" text,
	"default_practice_edi" text,
	"default_practice_name" text,
	"enrolment_end_date" text,
	"is_capitated" text,
	"is_consent_auto_reminder_text_messaging" text,
	"is_consent_for_experience_survey" text,
	"is_consent_to_import_clinical_records" text,
	"is_consent_to_private_email_address" text,
	"is_consent_to_share_clinical_records" text,
	"is_consent_to_share_health1" text,
	"is_consent_to_share_my_record_on_sehr" text,
	"is_consent_to_share_pho_data_collection" text,
	"is_include_account_fee" text,
	"is_include_statement_fee" text,
	"is_linked_csc_exists" text,
	"is_test_record" text,
	"pharmacy_id" text,
	"residential_status_id" text,
	"visa_expiry" text,
	"load_run_file_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "raw"."providers" (
	"provider_id" text,
	"practice_id" text,
	"nhi_number" text,
	"is_nhi_validate" boolean,
	"title" text,
	"first_name" text,
	"middle_name" text,
	"family_name" text,
	"full_name" text,
	"preferred_name" text,
	"other_maiden_name" text,
	"marital_status" text,
	"gender" text,
	"dob" text,
	"age" text,
	"age_type" text,
	"age_group" text,
	"is_alive" text,
	"death_date" text,
	"dob_source" text,
	"picture_path" text,
	"consentedto_share" text,
	"placeof_birth" text,
	"country_of_birth" text,
	"cell_number" text,
	"day_phone" text,
	"night_phone" text,
	"email" text,
	"secondary_email" text,
	"preferred_contact_method" text,
	"consent_text_messaging" text,
	"is_portal_user" text,
	"is_active" text,
	"is_deleted" text,
	"inserted_by" text,
	"updated_by" text,
	"inserted_at" text,
	"updated_at" text,
	"is_same_address" text,
	"notes" text,
	"is_gender_self_identified" text,
	"sex_related_gender" text,
	"is_worked_visa_required" text,
	"balance" text,
	"register_status" text,
	"med_tech_nok" text,
	"practice_name" text,
	"calculated_balance" text,
	"permanent_address" text,
	"deprivation_quintile" text,
	"uncertainty_code" text,
	"postal_address" text,
	"temporary_address" text,
	"city" text,
	"suburb" text,
	"portal_registration_status" text,
	"ethnicity" text,
	"affiliation_id" text,
	"affiliation" text,
	"affiliation_code" text,
	"nzmcno" text,
	"npi_no" text,
	"hbl_mat_payee_no" text,
	"hbl_mat_agree_no" text,
	"hpac_mat_agree_no" text,
	"hpac_mat_agree_ver" text,
	"hbl_payee_no" text,
	"hbl_gp_agree_no" text,
	"hbl_gp_agree_ver" text,
	"accreditation_no" text,
	"pho_contract_no" text,
	"pho_contract_ver" text,
	"group_id" text,
	"group_name" text,
	"acc_provider_code" text,
	"health_facility_no" text,
	"hpi_no" text,
	"unload_ref" text,
	"acc_provider_no" text,
	"acc_vendor_id" text,
	"pin_pan_no" text,
	"member_no" text,
	"rha_payee_no" text,
	"budget_no" text,
	"ipa" text,
	"registeration_no" text,
	"lab_no" text,
	"lab_tests_dr_id" text,
	"color_code" text,
	"is_doctor" text,
	"acc45_prefix" text,
	"next_acc45_no" text,
	"maximum_acc45_no" text,
	"aitc_prefix" text,
	"next_aitc_no" text,
	"maximum_aitc_no" text,
	"arc18_next_acc_form_no" text,
	"m45_prefix" text,
	"next_m45_no" text,
	"maximum_m45_no" text,
	"is_nzf_avoid" text,
	"is_nzf_adjust" text,
	"is_nzf_information" text,
	"is_nzf_no_action" text,
	"is_nzf_monitor" text,
	"provider_code" text,
	"generic_profile_type_id" text,
	"current_appointment_id" text,
	"sure_med_user_name" text,
	"is_invoicing_diary" text,
	"is_gp2gp" text,
	"from_date_practice" text,
	"apc_expiry_date" text,
	"mps_expiry_date" text,
	"apc_name" text,
	"practice_location" text,
	"user_role" text,
	"provider_permanent_address_latitude" text,
	"provider_permanent_address_longitude" text,
	"per_org_id" text,
	"loaded_date_time" text,
	"s3_bucket" text NOT NULL,
	"s3_key" text NOT NULL,
	"s3_version_id" text NOT NULL,
	"file_hash" text NOT NULL,
	"date_extracted" text NOT NULL,
	"extract_type" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "raw"."practice_info" (
	"practice_id" text,
	"practice_name" text,
	"practice_category" text,
	"practice_speciality" text,
	"pho" text,
	"organization_type" text,
	"org_short_name" text,
	"org_code" text,
	"edi_account" text,
	"legal_entity_title" text,
	"legal_status" text,
	"incorporation_number" text,
	"legal_date" text,
	"comments" text,
	"formula" text,
	"ownership_model" text,
	"rural" text,
	"primary_phone" text,
	"secondary_phone" text,
	"other_phone" text,
	"primary_email" text,
	"secondary_email" text,
	"other_email" text,
	"pager" text,
	"fax1" text,
	"fax2" text,
	"health_facility_no" text,
	"hpi_facility_no" text,
	"hpi_facility_ext" text,
	"hpi_organization_id" text,
	"hpi_organization_ext" text,
	"gst_no" text,
	"acc_no" text,
	"bank_account_no" text,
	"moh_sending_practice_id" text,
	"after_hours_number" text,
	"emergency_number" text,
	"is_active" text,
	"is_deleted" text,
	"per_org_id" text,
	"loaded_date_time" text,
	"s3_bucket" text NOT NULL,
	"s3_key" text NOT NULL,
	"s3_version_id" text NOT NULL,
	"file_hash" text NOT NULL,
	"date_extracted" text NOT NULL,
	"extract_type" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "raw"."appointments" (
	"appointment_id" text,
	"patient_id" text,
	"appointment_type" text,
	"appointment_status" text,
	"schedule_date" text,
	"notes" text,
	"arrived" text,
	"waiting_forpayment" text,
	"appointment_completed" text,
	"consult_time" text,
	"booked" text,
	"med_tech_id" text,
	"inserted_at" text,
	"inserted_by" text,
	"updated_at" text,
	"updated_by" text,
	"practice" text,
	"practice_id" text,
	"provider_id" text,
	"is_active" text,
	"is_deleted" text,
	"provider" text,
	"permanent_address_latitude" text,
	"permanent_address_longitude" text,
	"practice_location_id" text,
	"location_name" text,
	"reasonfor_visit" text,
	"status_group" text,
	"duration" text,
	"appointment_out_come_id" text,
	"appointment_out_come" text,
	"appointment_type_id" text,
	"booking_source_id" text,
	"booking_source" text,
	"consult_end_time" text,
	"consult_start_time" text,
	"consult_timer_status_id" text,
	"description" text,
	"end_time" text,
	"generated_time" text,
	"gp_queue_time" text,
	"is_arrived" text,
	"is_consult_parked" text,
	"is_dummy" text,
	"last_appointment_status_date" text,
	"last_appointment_status_id" text,
	"cancel_reason" text,
	"parked_reason" text,
	"priority_id" text,
	"arrived_time" text,
	"cancelled_time" text,
	"not_arrived_time" text,
	"nurse_queue_time" text,
	"on_hold_time" text,
	"read_only_time" text,
	"self_assessment_completed_time" text,
	"self_assessment_queue_time" text,
	"start_time" text,
	"triage_queue_time" text,
	"virtual_queue_time" text,
	"is_confidential" text,
	"is_consentto_share" text,
	"per_org_id" text,
	"loaded_date_time" text,
	"s3_bucket" text NOT NULL,
	"s3_key" text NOT NULL,
	"s3_version_id" text NOT NULL,
	"file_hash" text NOT NULL,
	"date_extracted" text NOT NULL,
	"extract_type" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "raw"."medicine" (
	"medicine_id" text,
	"medicine_name" text,
	"medicine_short_name" text,
	"sctid" text,
	"type" text,
	"pharma_code" text,
	"is_active" text,
	"is_deleted" text,
	"per_org_id" text,
	"practice_id" text,
	"loaded_date_time" text,
	"s3_bucket" text NOT NULL,
	"s3_key" text NOT NULL,
	"s3_version_id" text NOT NULL,
	"file_hash" text NOT NULL,
	"date_extracted" text NOT NULL,
	"extract_type" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "raw"."vaccine" (
	"vaccine_id" text,
	"vaccine_code" text,
	"vaccine_name" text,
	"long_description" text,
	"is_active" text,
	"is_deleted" text,
	"coding_system" text,
	"gender_id" text,
	"gender" text,
	"is_nir" text,
	"per_org_id" text,
	"practice_id" text,
	"loaded_date_time" text,
	"s3_bucket" text NOT NULL,
	"s3_key" text NOT NULL,
	"s3_version_id" text NOT NULL,
	"file_hash" text NOT NULL,
	"date_extracted" text NOT NULL,
	"extract_type" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "raw"."immunisation" (
	"appointment_immunisation_id" text,
	"patient_id" text,
	"appointment_id" text,
	"patient_schedule_id" text,
	"vaccine_id" text,
	"vaccine_name" text,
	"vaccine_code" text,
	"dose" text,
	"dose_number" text,
	"administration_site_id" text,
	"administration_site" text,
	"route_id" text,
	"route" text,
	"batch_number" text,
	"expiry_date" text,
	"immunisation_status_id" text,
	"immunisation_status" text,
	"vaccine_out_come_id" text,
	"vaccine_out_come" text,
	"is_nira_ck" text,
	"reason" text,
	"provider_id" text,
	"provider" text,
	"comments" text,
	"administration_time" text,
	"vaccine_indication_id" text,
	"vaccine_indication" text,
	"vaccine_indication_code" text,
	"needle_length" text,
	"has_diluent" text,
	"diluent_batch_no" text,
	"diluent_expiry_date" text,
	"is_confidential" text,
	"costing_code_id" text,
	"costing_code" text,
	"brand_id" text,
	"brand" text,
	"is_active" text,
	"is_deleted" text,
	"inserted_by_id" text,
	"inserted_by" text,
	"updated_by_id" text,
	"updated_by" text,
	"inserted_at" text,
	"updated_at" text,
	"is_parked" text,
	"med_tech_id" text,
	"practice_id" text,
	"practice" text,
	"is_auto_bill" text,
	"vaccinator_id" text,
	"vaccinator" text,
	"user_logging_id" text,
	"logging_user_name" text,
	"nir_sent_date" text,
	"show_on_portal" text,
	"vaccinator_code" text,
	"permanent_address_latitude" text,
	"permanent_address_longitude" text,
	"practice_location_id" text,
	"location_name" text,
	"vaccine_group_id" text,
	"vaccine_group" text,
	"per_org_id" text,
	"loaded_date_time" text,
	"s3_bucket" text NOT NULL,
	"s3_key" text NOT NULL,
	"s3_version_id" text NOT NULL,
	"file_hash" text NOT NULL,
	"date_extracted" text NOT NULL,
	"extract_type" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."patients" (
	"patient_id" text NOT NULL,
	"nhi_number" text,
	"is_nhi_validate" boolean,
	"title" text,
	"first_name" text,
	"middle_name" text,
	"family_name" text,
	"full_name" text,
	"preferred_name" text,
	"other_maiden_name" text,
	"marital_status_id" text,
	"marital_status" text,
	"gender_id" text,
	"gender" text,
	"dob" date,
	"age" integer,
	"age_type" text,
	"age_group" text,
	"is_alive" boolean,
	"death_date" date,
	"dob_source" text,
	"picture_path" text,
	"consented_to_share" boolean,
	"place_of_birth" text,
	"country_of_birth_id" text,
	"country_of_birth" text,
	"cell_number" text,
	"day_phone" text,
	"night_phone" text,
	"email" text,
	"secondary_email" text,
	"preferred_contact_method" text,
	"consent_text_messaging" boolean,
	"is_portal_user" boolean,
	"is_active" boolean,
	"is_deleted" boolean,
	"inserted_by" text,
	"updated_by" text,
	"inserted_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"notes" text,
	"is_gender_self_identified" boolean,
	"sex_related_gender" text,
	"is_worked_visa_required" boolean,
	"balance" numeric(10, 2),
	"med_tech_balance" numeric(10, 2),
	"med_tech_date_last_pay" date,
	"med_tech_date_last_stmt" date,
	"register_status_id" text,
	"register_status" text,
	"med_tech_nok" text,
	"practice_name" text,
	"calculated_balance" numeric(10, 2),
	"last_statement_date" date,
	"last_invoice_date" date,
	"last_payment_date" date,
	"provider_name" text,
	"chart_number" text,
	"extention" text,
	"practice_remarks" text,
	"is_insured" boolean,
	"insured_remarks" text,
	"smoking_type" text,
	"account_holder" text,
	"account_holder_employer" text,
	"is_community_service_card" boolean,
	"community_service_card_no" text,
	"community_service_card_exipry_date" date,
	"community_service_card_sighted" boolean,
	"is_health_card" boolean,
	"health_card_no" text,
	"health_card_expiry_date" date,
	"health_card_sighted" boolean,
	"winz" text,
	"is_transfer_of_records" boolean,
	"transfer_of_records_remarks" text,
	"enrolment_type" text,
	"enrolment_status_id" text,
	"enrolment_status" text,
	"enrolment_date" date,
	"enrolment_method" text,
	"enrolment_verifier" text,
	"funding_status_id" text,
	"funding_status" text,
	"rejection_reason" text,
	"funding_from" date,
	"funding_to" date,
	"account_group" text,
	"gms_code" text,
	"residential_status" text,
	"is_nka" boolean,
	"is_high_care" boolean,
	"high_care_reason" text,
	"is_care_plan" boolean,
	"is_new_registeration" boolean,
	"is_opt_off" boolean,
	"is_bp_graph" boolean,
	"is_bmi_graph" boolean,
	"is_inr_graph" boolean,
	"is_hba1c_graph" boolean,
	"asr_mark_status" text,
	"is_height_graph" boolean,
	"is_weight_graph" boolean,
	"is_hc_graph" boolean,
	"nes_status" text,
	"nes_comments" text,
	"med_tech_balance_date" date,
	"is_heart_rate" boolean,
	"is_premature" boolean,
	"premature_week" integer,
	"patient_pho_id" text,
	"consult_updated_at" timestamp with time zone,
	"occupation" text,
	"emergency_contact" text,
	"emergency_contact_name" text,
	"secondary_contact" text,
	"secondary_contact_name" text,
	"provider_id" text,
	"practice_id" text NOT NULL,
	"portal_registration_status" text,
	"registration_date" date,
	"med_tech_id" text,
	"permanent_address_house_number" text,
	"permanent_address_building_number" text,
	"permanent_address_street_number" text,
	"permanent_address_suburb_town_id" text,
	"permanent_address_suburb" text,
	"permanent_address_city_area_id" text,
	"permanent_address_city" text,
	"permanent_address_postal_code" text,
	"permanent_address_latitude" numeric(10, 8),
	"permanent_address_longitude" numeric(11, 8),
	"permanent_address_country_id" text,
	"permanent_address_country" text,
	"permanent_address" text,
	"permanent_address_dhb_code" text,
	"permanent_address_domicile_code" text,
	"permanent_address_deprivation_quintile" integer,
	"permanent_address_deprivation_decile" integer,
	"permanent_address_meshblock" text,
	"permanent_address_match_score" numeric(5, 2),
	"permanent_address_uncertainty_code" text,
	"temporary_address" text,
	"postal_address_house_number" text,
	"postal_address_building_number" text,
	"postal_address_street_number" text,
	"postal_address_suburb_town_id" text,
	"postal_address_suburb" text,
	"postal_address_city_area_id" text,
	"postal_address_city" text,
	"postal_address_postal_code" text,
	"postal_address_latitude" numeric(10, 8),
	"postal_address_longitude" numeric(11, 8),
	"postal_address_country_id" text,
	"postal_address_country" text,
	"postal_address" text,
	"postal_address_dhb_code" text,
	"postal_address_domicile_code" text,
	"postal_address_deprivation_quintile" integer,
	"postal_address_deprivation_decile" integer,
	"postal_address_meshblock" text,
	"postal_address_match_score" numeric(5, 2),
	"postal_address_uncertainty_code" text,
	"ethnicity_id" text,
	"ethnicity" text,
	"ethcode" text,
	"ethcode2" text,
	"secondary_ethnicity_id" text,
	"secondary_ethnicity" text,
	"ethcode3" text,
	"other_ethnicity_id" text,
	"other_ethnicity" text,
	"enrolment_id" text,
	"pho_name" text,
	"enrolment_expiry_date" date,
	"is_consent_to_share" boolean,
	"is_work_visa" boolean,
	"work_visa_start_date" date,
	"work_visa_expiry_date" date,
	"enrolment_quarter" text,
	"practice_location" text,
	"account_holder_type_id" text,
	"patient_type" text,
	"breast_screen_id" text,
	"breast_screen" text,
	"is_pregnant" boolean,
	"apply_charges" boolean,
	"include_in_print" boolean,
	"is_careplus" boolean,
	"care_plus_start_date" date,
	"care_plus_enddate" date,
	"care_plus_linc_status_id" text,
	"care_plus_linc_status" text,
	"nhi_status_id" text,
	"nhi_status" text,
	"per_org_id" text NOT NULL,
	"loaded_date_time" timestamp with time zone,
	"load_run_file_id" integer NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."providers" (
	"provider_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"nhi_number" text,
	"nzmc_no" text,
	"npi_no" text,
	"provider_code" text,
	"accreditation_no" text,
	"hpi_no" text,
	"title" text,
	"first_name" text,
	"middle_name" text,
	"family_name" text NOT NULL,
	"full_name" text NOT NULL,
	"preferred_name" text,
	"gender" text,
	"dob" date,
	"is_alive" boolean,
	"death_date" date,
	"practice_name" text,
	"user_role" text,
	"email" text,
	"cell_number" text,
	"is_active" boolean,
	"is_deleted" boolean,
	"inserted_by" text,
	"updated_by" text,
	"inserted_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"load_run_file_id" integer NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."practice_info" (
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"practice_name" text NOT NULL,
	"practice_category" text,
	"practice_speciality" text,
	"pho" text,
	"organization_type" text,
	"org_short_name" text,
	"org_code" text,
	"edi_account" text,
	"legal_entity_title" text,
	"legal_status" text,
	"incorporation_number" text,
	"ownership_model" text,
	"rural" boolean,
	"primary_phone" text,
	"secondary_phone" text,
	"primary_email" text,
	"secondary_email" text,
	"health_facility_no" text,
	"hpi_facility_no" text,
	"gst_no" text,
	"acc_no" text,
	"is_active" boolean,
	"is_deleted" boolean,
	"inserted_by" text,
	"updated_by" text,
	"inserted_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"load_run_file_id" integer NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."appointments" (
	"appointment_id" text NOT NULL,
	"patient_id" text,
	"appointment_type" text,
	"appointment_status" text,
	"schedule_date" timestamp,
	"notes" text,
	"arrived" boolean,
	"waiting_forpayment" boolean,
	"appointment_completed" boolean,
	"consult_time" integer,
	"booked" timestamp,
	"med_tech_id" text,
	"inserted_at" timestamp with time zone,
	"inserted_by" text,
	"updated_at" timestamp with time zone,
	"updated_by" text,
	"practice" text,
	"practice_id" text NOT NULL,
	"provider_id" text,
	"is_active" boolean,
	"is_deleted" boolean,
	"provider" text,
	"permanent_address_latitude" text,
	"permanent_address_longitude" text,
	"practice_location_id" text,
	"location_name" text,
	"reasonfor_visit" text,
	"status_group" text,
	"duration" integer,
	"appointment_out_come_id" text,
	"appointment_out_come" text,
	"appointment_type_id" text,
	"booking_source_id" text,
	"booking_source" text,
	"consult_end_time" timestamp,
	"consult_start_time" timestamp,
	"consult_timer_status_id" text,
	"description" text,
	"end_time" timestamp,
	"generated_time" timestamp,
	"gp_queue_time" integer,
	"is_arrived" boolean,
	"is_consult_parked" boolean,
	"is_dummy" boolean,
	"last_appointment_status_date" timestamp,
	"last_appointment_status_id" text,
	"cancel_reason" text,
	"parked_reason" text,
	"priority_id" text,
	"arrived_time" timestamp,
	"cancelled_time" timestamp,
	"not_arrived_time" timestamp,
	"nurse_queue_time" integer,
	"on_hold_time" integer,
	"read_only_time" integer,
	"self_assessment_completed_time" timestamp,
	"self_assessment_queue_time" integer,
	"start_time" timestamp,
	"triage_queue_time" integer,
	"virtual_queue_time" integer,
	"is_confidential" boolean,
	"is_consentto_share" boolean,
	"per_org_id" text NOT NULL,
	"loaded_date_time" timestamp with time zone,
	"load_run_file_id" integer NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."medicine" (
	"medicine_id" text NOT NULL,
	"medicine_name" text NOT NULL,
	"medicine_short_name" text,
	"sctid" text,
	"type" text,
	"pharma_code" text,
	"is_active" boolean,
	"is_deleted" boolean,
	"per_org_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"loaded_date_time" timestamp with time zone,
	"load_run_file_id" integer NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."vaccine" (
	"vaccine_id" text NOT NULL,
	"vaccine_code" text NOT NULL,
	"vaccine_name" text NOT NULL,
	"long_description" text,
	"is_active" boolean,
	"is_deleted" boolean,
	"coding_system" text,
	"gender_id" text,
	"gender" text,
	"is_nir" boolean,
	"per_org_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"loaded_date_time" timestamp with time zone,
	"load_run_file_id" integer NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."immunisation" (
	"appointment_immunisation_id" text NOT NULL,
	"patient_id" text,
	"appointment_id" text,
	"patient_schedule_id" text,
	"vaccine_id" text,
	"vaccine_name" text,
	"vaccine_code" text,
	"dose" text,
	"dose_number" integer,
	"administration_site_id" text,
	"administration_site" text,
	"route_id" text,
	"route" text,
	"batch_number" text,
	"expiry_date" date,
	"immunisation_status_id" text,
	"immunisation_status" text,
	"vaccine_out_come_id" text,
	"vaccine_out_come" text,
	"is_nira_ck" boolean,
	"reason" text,
	"provider_id" text,
	"provider" text,
	"comments" text,
	"administration_time" timestamp,
	"vaccine_indication_id" text,
	"vaccine_indication" text,
	"vaccine_indication_code" text,
	"needle_length" text,
	"has_diluent" boolean,
	"diluent_batch_no" text,
	"diluent_expiry_date" date,
	"is_confidential" boolean,
	"costing_code_id" text,
	"costing_code" text,
	"brand_id" text,
	"brand" text,
	"is_active" boolean,
	"is_deleted" boolean,
	"inserted_by_id" text,
	"inserted_by" text,
	"updated_by_id" text,
	"updated_by" text,
	"inserted_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"is_parked" boolean,
	"med_tech_id" text,
	"practice_id" text NOT NULL,
	"practice" text,
	"is_auto_bill" boolean,
	"vaccinator_id" text,
	"vaccinator" text,
	"user_logging_id" text,
	"logging_user_name" text,
	"nir_sent_date" timestamp,
	"show_on_portal" boolean,
	"vaccinator_code" text,
	"permanent_address_latitude" text,
	"permanent_address_longitude" text,
	"practice_location_id" text,
	"location_name" text,
	"vaccine_group_id" text,
	"vaccine_group" text,
	"per_org_id" text NOT NULL,
	"loaded_date_time" timestamp with time zone,
	"load_run_file_id" integer NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core"."medicine" (
	"medicine_key" serial PRIMARY KEY NOT NULL,
	"medicine_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"effective_from" timestamp with time zone NOT NULL,
	"effective_to" timestamp with time zone,
	"is_current" boolean DEFAULT true NOT NULL,
	"medicine_name" text NOT NULL,
	"medicine_short_name" text,
	"sctid" text,
	"type" text,
	"pharma_code" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core"."patient" (
	"patient_key" serial PRIMARY KEY NOT NULL,
	"patient_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"nhi_number" text,
	"title" text,
	"first_name" text,
	"middle_name" text,
	"family_name" text,
	"full_name" text,
	"preferred_name" text,
	"gender" text,
	"dob" date,
	"age" integer,
	"age_group" text,
	"is_alive" boolean DEFAULT true NOT NULL,
	"death_date" date,
	"marital_status" text,
	"ethnicity" text,
	"residential_status" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"cell_number" text,
	"day_phone" text,
	"night_phone" text,
	"email" text,
	"permanent_address_city" text,
	"permanent_address_suburb" text,
	"permanent_address_postal_code" text,
	"permanent_address_dhb_code" text,
	"permanent_address_deprivation_quintile" integer,
	"provider_id" text,
	"practice_name" text,
	"effective_from" timestamp with time zone NOT NULL,
	"effective_to" timestamp with time zone,
	"is_current" boolean DEFAULT true NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core"."practice" (
	"practice_key" serial PRIMARY KEY NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"effective_from" timestamp with time zone NOT NULL,
	"effective_to" timestamp with time zone,
	"is_current" boolean DEFAULT true NOT NULL,
	"practice_name" text NOT NULL,
	"practice_category" text,
	"practice_speciality" text,
	"pho" text,
	"organization_type" text,
	"org_short_name" text,
	"org_code" text,
	"edi_account" text,
	"legal_entity_title" text,
	"legal_status" text,
	"incorporation_number" text,
	"ownership_model" text,
	"rural" boolean DEFAULT false NOT NULL,
	"primary_phone" text,
	"secondary_phone" text,
	"primary_email" text,
	"secondary_email" text,
	"health_facility_no" text,
	"hpi_facility_no" text,
	"gst_no" text,
	"acc_no" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core"."provider" (
	"provider_key" serial PRIMARY KEY NOT NULL,
	"provider_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"nhi_number" text,
	"title" text,
	"first_name" text,
	"middle_name" text,
	"family_name" text NOT NULL,
	"full_name" text NOT NULL,
	"preferred_name" text,
	"gender" text,
	"dob" date,
	"is_alive" boolean DEFAULT true NOT NULL,
	"death_date" date,
	"nzmc_no" text,
	"npi_no" text,
	"provider_code" text,
	"accreditation_no" text,
	"hpi_no" text,
	"practice_name" text,
	"user_role" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"effective_from" timestamp with time zone NOT NULL,
	"effective_to" timestamp with time zone,
	"is_current" boolean DEFAULT true NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core"."vaccine" (
	"vaccine_key" serial PRIMARY KEY NOT NULL,
	"vaccine_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"effective_from" timestamp with time zone NOT NULL,
	"effective_to" timestamp with time zone,
	"is_current" boolean DEFAULT true NOT NULL,
	"vaccine_code" text NOT NULL,
	"vaccine_name" text NOT NULL,
	"long_description" text,
	"coding_system" text,
	"gender" text,
	"is_nir" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core"."fact_appointment" (
	"appointment_key" serial PRIMARY KEY NOT NULL,
	"appointment_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"patient_key" integer,
	"provider_key" integer,
	"practice_key" integer,
	"appointment_type" text,
	"appointment_status" text,
	"schedule_date" timestamp,
	"duration" integer,
	"consult_time" integer,
	"arrived" boolean DEFAULT false NOT NULL,
	"appointment_completed" boolean DEFAULT false NOT NULL,
	"is_confidential" boolean DEFAULT false NOT NULL,
	"appointment_notes" text,
	"reason_for_visit" text,
	"follow_up_required" boolean DEFAULT false NOT NULL,
	"s3_version_id" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core"."fact_diagnosis" (
	"diagnosis_key" serial PRIMARY KEY NOT NULL,
	"diagnosis_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"patient_key" integer,
	"provider_key" integer,
	"diagnosis_date" date,
	"icd10_code" text,
	"diagnosis_description" text,
	"diagnosis_type" text,
	"certainty" text,
	"is_chronic" boolean DEFAULT false NOT NULL,
	"is_resolved" boolean DEFAULT false NOT NULL,
	"onset_date" date,
	"resolved_date" date,
	"s3_version_id" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core"."fact_immunisation" (
	"immunisation_key" serial PRIMARY KEY NOT NULL,
	"immunisation_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"patient_key" integer,
	"provider_key" integer,
	"vaccine_key" integer,
	"immunisation_date" date,
	"batch_number" text,
	"expiry_date" date,
	"dose" numeric(10, 2),
	"dose_unit" text,
	"route" text,
	"site" text,
	"sequence" integer,
	"is_valid" boolean DEFAULT true NOT NULL,
	"validation_error" text,
	"is_historical" boolean DEFAULT false NOT NULL,
	"s3_version_id" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core"."fact_invoice" (
	"invoice_key" serial PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"patient_key" integer,
	"provider_key" integer,
	"invoice_date" date,
	"due_date" date,
	"paid_date" date,
	"gross_amount" numeric(10, 2),
	"discount_amount" numeric(10, 2),
	"tax_amount" numeric(10, 2),
	"net_amount" numeric(10, 2),
	"paid_amount" numeric(10, 2),
	"outstanding_amount" numeric(10, 2),
	"status" text,
	"payment_method" text,
	"is_overdue" boolean DEFAULT false NOT NULL,
	"s3_version_id" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "fact_invoice_business_key_idx" UNIQUE("invoice_id","practice_id","per_org_id")
);
--> statement-breakpoint
CREATE TABLE "core"."fact_invoice_detail" (
	"invoice_detail_key" serial PRIMARY KEY NOT NULL,
	"invoice_detail_id" text NOT NULL,
	"invoice_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"patient_key" integer,
	"provider_key" integer,
	"medicine_key" integer,
	"service_date" date,
	"service_code" text,
	"service_description" text,
	"quantity" numeric(10, 2),
	"unit_price" numeric(10, 2),
	"line_total" numeric(10, 2),
	"is_refunded" boolean DEFAULT false NOT NULL,
	"refund_amount" numeric(10, 2),
	"s3_version_id" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core"."fact_measurement" (
	"measurement_key" serial PRIMARY KEY NOT NULL,
	"measurement_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"per_org_id" text NOT NULL,
	"patient_key" integer,
	"provider_key" integer,
	"measurement_date" timestamp,
	"measurement_type" text,
	"measurement_code" text,
	"measurement_value" numeric(10, 4),
	"unit" text,
	"normal_range_low" numeric(10, 4),
	"normal_range_high" numeric(10, 4),
	"is_abnormal" boolean DEFAULT false NOT NULL,
	"interpretation" text,
	"notes" text,
	"s3_version_id" text NOT NULL,
	"load_run_id" uuid NOT NULL,
	"load_ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "etl"."core_merge_runs" (
	"merge_run_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"load_run_id" uuid NOT NULL,
	"staging_run_id" uuid NOT NULL,
	"extract_type" text NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"status" text NOT NULL,
	"dimensions_created" integer DEFAULT 0,
	"dimensions_updated" integer DEFAULT 0,
	"facts_inserted" integer DEFAULT 0,
	"facts_updated" integer DEFAULT 0,
	"error" text,
	"result" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "etl"."load_run_files" (
	"load_run_file_id" serial PRIMARY KEY NOT NULL,
	"load_run_id" uuid NOT NULL,
	"s3_bucket" text NOT NULL,
	"s3_key" text NOT NULL,
	"s3_version_id" text NOT NULL,
	"file_hash" text NOT NULL,
	"date_extracted" text NOT NULL,
	"extract_type" text NOT NULL,
	"per_org_id" text NOT NULL,
	"practice_id" text NOT NULL,
	"rows_read" integer DEFAULT 0,
	"rows_ingested" integer DEFAULT 0,
	"rows_rejected" integer DEFAULT 0,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"status" text NOT NULL,
	"error_message" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "etl"."load_runs" (
	"load_run_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"status" text NOT NULL,
	"triggered_by" text NOT NULL,
	"notes" text,
	"total_files_processed" integer DEFAULT 0,
	"total_rows_ingested" integer DEFAULT 0,
	"total_rows_rejected" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "etl"."staging_runs" (
	"staging_run_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"load_run_id" uuid NOT NULL,
	"extract_type" text NOT NULL,
	"source_table" text NOT NULL,
	"target_table" text NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"status" text NOT NULL,
	"total_rows_read" integer DEFAULT 0,
	"total_rows_transformed" integer DEFAULT 0,
	"total_rows_rejected" integer DEFAULT 0,
	"total_rows_deduplicated" integer DEFAULT 0,
	"successful_batches" integer DEFAULT 0,
	"failed_batches" integer DEFAULT 0,
	"duration_ms" integer,
	"rows_per_second" integer,
	"memory_usage_mb" integer,
	"error" text,
	"result" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "core"."fact_appointment" ADD CONSTRAINT "fact_appointment_patient_key_patient_patient_key_fk" FOREIGN KEY ("patient_key") REFERENCES "core"."patient"("patient_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_appointment" ADD CONSTRAINT "fact_appointment_provider_key_provider_provider_key_fk" FOREIGN KEY ("provider_key") REFERENCES "core"."provider"("provider_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_appointment" ADD CONSTRAINT "fact_appointment_practice_key_practice_practice_key_fk" FOREIGN KEY ("practice_key") REFERENCES "core"."practice"("practice_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_diagnosis" ADD CONSTRAINT "fact_diagnosis_patient_key_patient_patient_key_fk" FOREIGN KEY ("patient_key") REFERENCES "core"."patient"("patient_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_diagnosis" ADD CONSTRAINT "fact_diagnosis_provider_key_provider_provider_key_fk" FOREIGN KEY ("provider_key") REFERENCES "core"."provider"("provider_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_immunisation" ADD CONSTRAINT "fact_immunisation_patient_key_patient_patient_key_fk" FOREIGN KEY ("patient_key") REFERENCES "core"."patient"("patient_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_immunisation" ADD CONSTRAINT "fact_immunisation_provider_key_provider_provider_key_fk" FOREIGN KEY ("provider_key") REFERENCES "core"."provider"("provider_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_immunisation" ADD CONSTRAINT "fact_immunisation_vaccine_key_vaccine_vaccine_key_fk" FOREIGN KEY ("vaccine_key") REFERENCES "core"."vaccine"("vaccine_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_invoice" ADD CONSTRAINT "fact_invoice_patient_key_patient_patient_key_fk" FOREIGN KEY ("patient_key") REFERENCES "core"."patient"("patient_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_invoice" ADD CONSTRAINT "fact_invoice_provider_key_provider_provider_key_fk" FOREIGN KEY ("provider_key") REFERENCES "core"."provider"("provider_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_invoice_detail" ADD CONSTRAINT "fact_invoice_detail_patient_key_patient_patient_key_fk" FOREIGN KEY ("patient_key") REFERENCES "core"."patient"("patient_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_invoice_detail" ADD CONSTRAINT "fact_invoice_detail_provider_key_provider_provider_key_fk" FOREIGN KEY ("provider_key") REFERENCES "core"."provider"("provider_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_invoice_detail" ADD CONSTRAINT "fact_invoice_detail_medicine_key_medicine_medicine_key_fk" FOREIGN KEY ("medicine_key") REFERENCES "core"."medicine"("medicine_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_invoice_detail" ADD CONSTRAINT "fk_invoice_detail_invoice" FOREIGN KEY ("invoice_id","practice_id","per_org_id") REFERENCES "core"."fact_invoice"("invoice_id","practice_id","per_org_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_measurement" ADD CONSTRAINT "fact_measurement_patient_key_patient_patient_key_fk" FOREIGN KEY ("patient_key") REFERENCES "core"."patient"("patient_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."fact_measurement" ADD CONSTRAINT "fact_measurement_provider_key_provider_provider_key_fk" FOREIGN KEY ("provider_key") REFERENCES "core"."provider"("provider_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "etl"."core_merge_runs" ADD CONSTRAINT "core_merge_runs_load_run_id_load_runs_load_run_id_fk" FOREIGN KEY ("load_run_id") REFERENCES "etl"."load_runs"("load_run_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "etl"."core_merge_runs" ADD CONSTRAINT "core_merge_runs_staging_run_id_staging_runs_staging_run_id_fk" FOREIGN KEY ("staging_run_id") REFERENCES "etl"."staging_runs"("staging_run_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "etl"."load_run_files" ADD CONSTRAINT "load_run_files_load_run_id_load_runs_load_run_id_fk" FOREIGN KEY ("load_run_id") REFERENCES "etl"."load_runs"("load_run_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "etl"."staging_runs" ADD CONSTRAINT "staging_runs_load_run_id_load_runs_load_run_id_fk" FOREIGN KEY ("load_run_id") REFERENCES "etl"."load_runs"("load_run_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "patients_stg_natural_key_idx" ON "stg"."patients" USING btree ("patient_id","practice_id","per_org_id");--> statement-breakpoint
CREATE UNIQUE INDEX "providers_stg_natural_key_idx" ON "stg"."providers" USING btree ("provider_id","practice_id","per_org_id");--> statement-breakpoint
CREATE UNIQUE INDEX "practice_info_stg_natural_key_idx" ON "stg"."practice_info" USING btree ("practice_id","per_org_id");--> statement-breakpoint
CREATE UNIQUE INDEX "appointments_stg_natural_key_idx" ON "stg"."appointments" USING btree ("appointment_id","practice_id","per_org_id");--> statement-breakpoint
CREATE UNIQUE INDEX "medicine_stg_natural_key_idx" ON "stg"."medicine" USING btree ("medicine_id","practice_id","per_org_id");--> statement-breakpoint
CREATE UNIQUE INDEX "vaccine_stg_natural_key_idx" ON "stg"."vaccine" USING btree ("vaccine_id","practice_id","per_org_id");--> statement-breakpoint
CREATE UNIQUE INDEX "immunisation_stg_natural_key_idx" ON "stg"."immunisation" USING btree ("appointment_immunisation_id","practice_id","per_org_id");--> statement-breakpoint
CREATE UNIQUE INDEX "dim_medicine_business_key_current_idx" ON "core"."medicine" USING btree ("medicine_id","practice_id","per_org_id","is_current");--> statement-breakpoint
CREATE UNIQUE INDEX "dim_patient_business_key_current_idx" ON "core"."patient" USING btree ("patient_id","practice_id","per_org_id","is_current");--> statement-breakpoint
CREATE UNIQUE INDEX "dim_practice_business_key_current_idx" ON "core"."practice" USING btree ("practice_id","per_org_id","is_current");--> statement-breakpoint
CREATE UNIQUE INDEX "dim_provider_business_key_current_idx" ON "core"."provider" USING btree ("provider_id","practice_id","per_org_id","is_current");--> statement-breakpoint
CREATE UNIQUE INDEX "dim_vaccine_business_key_current_idx" ON "core"."vaccine" USING btree ("vaccine_id","practice_id","per_org_id","is_current");--> statement-breakpoint
CREATE UNIQUE INDEX "fact_appointment_business_key_idx" ON "core"."fact_appointment" USING btree ("appointment_id","practice_id","per_org_id");--> statement-breakpoint
CREATE INDEX "fact_appointment_patient_key_idx" ON "core"."fact_appointment" USING btree ("patient_key");--> statement-breakpoint
CREATE INDEX "fact_appointment_provider_key_idx" ON "core"."fact_appointment" USING btree ("provider_key");--> statement-breakpoint
CREATE INDEX "fact_appointment_schedule_date_idx" ON "core"."fact_appointment" USING btree ("schedule_date");--> statement-breakpoint
CREATE UNIQUE INDEX "fact_diagnosis_business_key_idx" ON "core"."fact_diagnosis" USING btree ("diagnosis_id","practice_id","per_org_id");--> statement-breakpoint
CREATE INDEX "fact_diagnosis_patient_key_idx" ON "core"."fact_diagnosis" USING btree ("patient_key");--> statement-breakpoint
CREATE INDEX "fact_diagnosis_icd10_code_idx" ON "core"."fact_diagnosis" USING btree ("icd10_code");--> statement-breakpoint
CREATE INDEX "fact_diagnosis_date_idx" ON "core"."fact_diagnosis" USING btree ("diagnosis_date");--> statement-breakpoint
CREATE UNIQUE INDEX "fact_immunisation_business_key_idx" ON "core"."fact_immunisation" USING btree ("immunisation_id","practice_id","per_org_id");--> statement-breakpoint
CREATE INDEX "fact_immunisation_patient_key_idx" ON "core"."fact_immunisation" USING btree ("patient_key");--> statement-breakpoint
CREATE INDEX "fact_immunisation_vaccine_key_idx" ON "core"."fact_immunisation" USING btree ("vaccine_key");--> statement-breakpoint
CREATE INDEX "fact_immunisation_date_idx" ON "core"."fact_immunisation" USING btree ("immunisation_date");--> statement-breakpoint
CREATE INDEX "fact_invoice_patient_key_idx" ON "core"."fact_invoice" USING btree ("patient_key");--> statement-breakpoint
CREATE INDEX "fact_invoice_date_idx" ON "core"."fact_invoice" USING btree ("invoice_date");--> statement-breakpoint
CREATE INDEX "fact_invoice_status_idx" ON "core"."fact_invoice" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "fact_invoice_detail_business_key_idx" ON "core"."fact_invoice_detail" USING btree ("invoice_detail_id","practice_id","per_org_id");--> statement-breakpoint
CREATE INDEX "fact_invoice_detail_invoice_id_idx" ON "core"."fact_invoice_detail" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "fact_invoice_detail_medicine_key_idx" ON "core"."fact_invoice_detail" USING btree ("medicine_key");--> statement-breakpoint
CREATE UNIQUE INDEX "fact_measurement_business_key_idx" ON "core"."fact_measurement" USING btree ("measurement_id","practice_id","per_org_id");--> statement-breakpoint
CREATE INDEX "fact_measurement_patient_key_idx" ON "core"."fact_measurement" USING btree ("patient_key");--> statement-breakpoint
CREATE INDEX "fact_measurement_type_idx" ON "core"."fact_measurement" USING btree ("measurement_type");--> statement-breakpoint
CREATE INDEX "fact_measurement_date_idx" ON "core"."fact_measurement" USING btree ("measurement_date");--> statement-breakpoint
CREATE UNIQUE INDEX "core_merge_runs_staging_run_completed_idx" ON "etl"."core_merge_runs" USING btree ("staging_run_id") WHERE "etl"."core_merge_runs"."status" = 'completed';--> statement-breakpoint
CREATE INDEX "core_merge_runs_status_idx" ON "etl"."core_merge_runs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "core_merge_runs_load_run_idx" ON "etl"."core_merge_runs" USING btree ("load_run_id");--> statement-breakpoint
CREATE INDEX "core_merge_runs_staging_run_idx" ON "etl"."core_merge_runs" USING btree ("staging_run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "load_run_files_unique_idx" ON "etl"."load_run_files" USING btree ("s3_version_id","file_hash");--> statement-breakpoint
CREATE INDEX "load_run_files_load_run_idx" ON "etl"."load_run_files" USING btree ("load_run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "staging_runs_load_run_completed_idx" ON "etl"."staging_runs" USING btree ("load_run_id","extract_type") WHERE "etl"."staging_runs"."status" = 'completed';--> statement-breakpoint
CREATE INDEX "staging_runs_status_idx" ON "etl"."staging_runs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "staging_runs_load_run_idx" ON "etl"."staging_runs" USING btree ("load_run_id");