import { BaseSchemaDrivenHandler } from "../schema-driven-handler";
import type { ValidationRule } from "../types/raw-loader";

/**
 * Providers handler generated from schema
 * Generated on 2025-10-06T01:11:46.106Z
 */
export class ProvidersSchemaHandler extends BaseSchemaDrivenHandler {
  extractType = "Provider";
  tableName = "raw.providers";

  // Generated from src/db/schema/raw/providers.ts
  columnMapping = [
    'provider_id',
    'practice_id',
    'nhi_number',
    'is_nhi_validate',
    'title',
    'first_name',
    'middle_name',
    'family_name',
    'full_name',
    'preferred_name',
    'other_maiden_name',
    'marital_status',
    'gender',
    'dob',
    'age',
    'age_type',
    'age_group',
    'is_alive',
    'death_date',
    'dob_source',
    'picture_path',
    'consentedto_share',
    'placeof_birth',
    'country_of_birth',
    'cell_number',
    'day_phone',
    'night_phone',
    'email',
    'secondary_email',
    'preferred_contact_method',
    'consent_text_messaging',
    'is_portal_user',
    'is_active',
    'is_deleted',
    'inserted_by',
    'updated_by',
    'inserted_at',
    'updated_at',
    'is_same_address',
    'notes',
    'is_gender_self_identified',
    'sex_related_gender',
    'is_worked_visa_required',
    'balance',
    'register_status',
    'med_tech_nok',
    'practice_name',
    'calculated_balance',
    'permanent_address',
    'deprivation_quintile',
    'uncertainty_code',
    'postal_address',
    'temporary_address',
    'city',
    'suburb',
    'portal_registration_status',
    'ethnicity',
    'affiliation_id',
    'affiliation',
    'affiliation_code',
    'nzmcno',
    'npi_no',
    'hbl_mat_payee_no',
    'hbl_mat_agree_no',
    'hpac_mat_agree_no',
    'hpac_mat_agree_ver',
    'hbl_payee_no',
    'hbl_gp_agree_no',
    'hbl_gp_agree_ver',
    'accreditation_no',
    'pho_contract_no',
    'pho_contract_ver',
    'group_id',
    'group_name',
    'acc_provider_code',
    'health_facility_no',
    'hpi_no',
    'unload_ref',
    'acc_provider_no',
    'acc_vendor_id',
    'pin_pan_no',
    'member_no',
    'rha_payee_no',
    'budget_no',
    'ipa',
    'registeration_no',
    'lab_no',
    'lab_tests_dr_id',
    'color_code',
    'is_doctor',
    'acc_45_prefix',
    'next_acc_45_no',
    'maximum_acc_45_no',
    'aitc_prefix',
    'next_aitc_no',
    'maximum_aitc_no',
    'arc_18_next_acc_form_no',
    'm_45_prefix',
    'next_m_45_no',
    'maximum_m_45_no',
    'is_nzf_avoid',
    'is_nzf_adjust',
    'is_nzf_information',
    'is_nzf_no_action',
    'is_nzf_monitor',
    'provider_code',
    'generic_profile_type_id',
    'current_appointment_id',
    'sure_med_user_name',
    'is_invoicing_diary',
    'is_gp2gp',
    'from_date_practice',
    'apc_expiry_date',
    'mps_expiry_date',
    'apc_name',
    'practice_location',
    'user_role',
    'provider_permanent_address_latitude',
    'per_org_id',
    'loaded_date_time',
    'load_run_file_id',
    's3_bucket',
    's3_key',
    's3_version_id',
    'file_hash',
    'date_extracted',
    'extract_type',
    'load_run_id',
    'load_ts'
];

  validationRules: ValidationRule[] = [
    // TODO: Add entity-specific validation rules
    // Example:
    // {
    //   columnName: "provider_id",
    //   ruleType: "required",
    //   validator: (value) => /^\d+$/.test(value),
    //   errorMessage: "provider_id must be numeric"
    // }
  ];
}
