import type { ColumnTransformation } from "../types/transformer";
import { ColumnType } from "../types/transformer";

/**
 * Inbox staging transformations
 * Converts raw text columns to typed staging columns
 */
export const inboxTransformations: ColumnTransformation[] = [
  // IDs - Keep as text
  {
    sourceColumn: "inbox_folder_item_id",
    targetColumn: "inboxFolderItemId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "per_org_id",
    targetColumn: "perOrgId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "practice_id",
    targetColumn: "practiceId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "folder_id",
    targetColumn: "folderId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "folder_name",
    targetColumn: "folderName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "is_system_folder",
    targetColumn: "isSystemFolder",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "order_no",
    targetColumn: "orderNo",
    targetType: ColumnType.INTEGER,
    required: false,
  },
  {
    sourceColumn: "item_type_id",
    targetColumn: "itemTypeId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "item_type",
    targetColumn: "itemType",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "patient_id",
    targetColumn: "patientId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "provider_id",
    targetColumn: "providerId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "patient_name",
    targetColumn: "patientName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "provider",
    targetColumn: "provider",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "practice_name",
    targetColumn: "practiceName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "from_org_id",
    targetColumn: "fromOrgId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "from_organization_name",
    targetColumn: "fromOrganizationName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "assign_to_id",
    targetColumn: "assignToId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "assign_to",
    targetColumn: "assignTo",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "result_date",
    targetColumn: "resultDate",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "message_subject_id",
    targetColumn: "messageSubjectId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "message_subject",
    targetColumn: "messageSubject",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "comments",
    targetColumn: "comments",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "mark_as_read",
    targetColumn: "markAsRead",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_confidential",
    targetColumn: "isConfidential",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "show_on_portal",
    targetColumn: "showOnPortal",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_reviewed",
    targetColumn: "isReviewed",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "show_on_time_line",
    targetColumn: "showOnTimeLine",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_active",
    targetColumn: "isActive",
    targetType: ColumnType.BOOLEAN,
    required: false,
    defaultValue: true,
  },
  {
    sourceColumn: "is_deleted",
    targetColumn: "isDeleted",
    targetType: ColumnType.BOOLEAN,
    required: false,
    defaultValue: false,
  },
  {
    sourceColumn: "inserted_by_id",
    targetColumn: "insertedById",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "inserted_by",
    targetColumn: "insertedBy",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "updated_by_id",
    targetColumn: "updatedById",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "updated_by",
    targetColumn: "updatedBy",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "inserted_at",
    targetColumn: "insertedAt",
    targetType: ColumnType.TIMESTAMP,
    required: false,
  },
  {
    sourceColumn: "updated_at",
    targetColumn: "updatedAt",
    targetType: ColumnType.TIMESTAMP,
    required: false,
  },
  {
    sourceColumn: "med_tech_id",
    targetColumn: "medTechId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "dms_id",
    targetColumn: "dmsId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "is_repeat_rx",
    targetColumn: "isRepeatRx",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_replied_rx",
    targetColumn: "isRepliedRx",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "external_ref",
    targetColumn: "externalRef",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "abnorm_result",
    targetColumn: "abnormResult",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "is_deactivated",
    targetColumn: "isDeactivated",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "folder_group",
    targetColumn: "folderGroup",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "document_code",
    targetColumn: "documentCode",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "is_gp2gp",
    targetColumn: "isGp2Gp",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "informat_id",
    targetColumn: "informatId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "informat",
    targetColumn: "informat",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "permanent_address_latitude",
    targetColumn: "permanentAddressLatitude",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "permanent_address_longitude",
    targetColumn: "permanentAddressLongitude",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "filed_at",
    targetColumn: "filedAt",
    targetType: ColumnType.TIMESTAMP,
    required: false,
  },
  {
    sourceColumn: "loaded_date_time",
    targetColumn: "loadedDateTime",
    targetType: ColumnType.TIMESTAMP,
    required: false,
  },
];
