import type { ColumnTransformation } from "../types/transformer";
import { ColumnType } from "../types/transformer";

/**
 * InvoiceDetail staging transformations
 * Converts raw text columns to typed staging columns
 */
export const invoiceDetailTransformations: ColumnTransformation[] = [
  // IDs - Keep as text
  {
    sourceColumn: "invoice_detail_id",
    targetColumn: "invoiceDetailId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "invoice_transaction_id",
    targetColumn: "invoiceTransactionId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "master_service_sub_service_id",
    targetColumn: "masterServiceSubServiceId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "appointment_service_id",
    targetColumn: "appointmentServiceId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "comments",
    targetColumn: "comments",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "quantity",
    targetColumn: "quantity",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "claim_amount",
    targetColumn: "claimAmount",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "co_payment",
    targetColumn: "coPayment",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "gross_claim_amount",
    targetColumn: "grossClaimAmount",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "gross_co_payment",
    targetColumn: "grossCoPayment",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "is_billing_amount",
    targetColumn: "isBillingAmount",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "funder_id",
    targetColumn: "funderId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "funder_name",
    targetColumn: "funderName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "contract_service_id",
    targetColumn: "contractServiceId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "contract_service_name",
    targetColumn: "contractServiceName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "is_funded",
    targetColumn: "isFunded",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "submission_status",
    targetColumn: "submissionStatus",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "case_no",
    targetColumn: "caseNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "sequence_no",
    targetColumn: "sequenceNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "billing_claim_status_id",
    targetColumn: "billingClaimStatusId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "master_service_name",
    targetColumn: "masterServiceName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "master_service_code",
    targetColumn: "masterServiceCode",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "master_service_description",
    targetColumn: "masterServiceDescription",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "service_name",
    targetColumn: "serviceName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "description",
    targetColumn: "description",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "code",
    targetColumn: "code",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "fee_code",
    targetColumn: "feeCode",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "service_code",
    targetColumn: "serviceCode",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "sub_service_description",
    targetColumn: "subServiceDescription",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "duration",
    targetColumn: "duration",
    targetType: ColumnType.INTEGER,
    required: false,
  },
  {
    sourceColumn: "is_common_service",
    targetColumn: "isCommonService",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "service_code_for_claim",
    targetColumn: "serviceCodeForClaim",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "is_active",
    targetColumn: "isActive",
    targetType: ColumnType.BOOLEAN,
    required: false,
    defaultValue: true,
  },
  {
    sourceColumn: "is_deleted",
    targetColumn: "isDeleted",
    targetType: ColumnType.BOOLEAN,
    required: false,
    defaultValue: false,
  },
  {
    sourceColumn: "inserted_by_id",
    targetColumn: "insertedById",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "updated_by_id",
    targetColumn: "updatedById",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "inserted_by",
    targetColumn: "insertedBy",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "updated_by",
    targetColumn: "updatedBy",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "inserted_at",
    targetColumn: "insertedAt",
    targetType: ColumnType.TIMESTAMP,
    required: false,
  },
  {
    sourceColumn: "updated_at",
    targetColumn: "updatedAt",
    targetType: ColumnType.TIMESTAMP,
    required: false,
  },
  {
    sourceColumn: "user_logging_id",
    targetColumn: "userLoggingId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "logging_user_name",
    targetColumn: "loggingUserName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "billing_ref_id",
    targetColumn: "billingRefId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "billing_referral_id",
    targetColumn: "billingReferralId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_latitude",
    targetColumn: "permanentAddressLatitude",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "permanent_address_longitude",
    targetColumn: "permanentAddressLongitude",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "practice_id",
    targetColumn: "practiceId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "per_org_id",
    targetColumn: "perOrgId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "loaded_date_time",
    targetColumn: "loadedDateTime",
    targetType: ColumnType.TIMESTAMP,
    required: false,
  },
];
