import type { ColumnTransformation } from "../types/transformer";
import { ColumnType } from "../types/transformer";

/**
 * Measurements staging transformations
 * Converts raw text columns to typed staging columns
 */
export const measurementsTransformations: ColumnTransformation[] = [
  // IDs - Keep as text
  {
    sourceColumn: "patient_id",
    targetColumn: "patientId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "screening_id",
    targetColumn: "screeningId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "appointment_id",
    targetColumn: "appointmentId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "screening_date",
    targetColumn: "screeningDate",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "scncode",
    targetColumn: "scncode",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "screening_type",
    targetColumn: "screeningType",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "screening_group",
    targetColumn: "screeningGroup",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "outcome",
    targetColumn: "outcome",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "outcome_description",
    targetColumn: "outcomeDescription",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "notes",
    targetColumn: "notes",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "is_active",
    targetColumn: "isActive",
    targetType: ColumnType.BOOLEAN,
    required: false,
    defaultValue: true,
  },
  {
    sourceColumn: "updated_by_id",
    targetColumn: "updatedById",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "updated_by",
    targetColumn: "updatedBy",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "updated_at",
    targetColumn: "updatedAt",
    targetType: ColumnType.TIMESTAMP,
    required: false,
  },
  {
    sourceColumn: "inserted_by_id",
    targetColumn: "insertedById",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "inserted_by",
    targetColumn: "insertedBy",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "inserted_at",
    targetColumn: "insertedAt",
    targetType: ColumnType.TIMESTAMP,
    required: false,
  },
  {
    sourceColumn: "patient_med_tech_id",
    targetColumn: "patientMedTechId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "practice",
    targetColumn: "practice",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "practice_id",
    targetColumn: "practiceId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "provider_id",
    targetColumn: "providerId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "provider_code",
    targetColumn: "providerCode",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "provider_name",
    targetColumn: "providerName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "hba1c",
    targetColumn: "hba1c",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "is_deleted",
    targetColumn: "isDeleted",
    targetType: ColumnType.BOOLEAN,
    required: false,
    defaultValue: false,
  },
  {
    sourceColumn: "care_plan_id",
    targetColumn: "carePlanId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "care_plane_name",
    targetColumn: "carePlaneName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "is_confidential",
    targetColumn: "isConfidential",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_gp2gp",
    targetColumn: "isGp2Gp",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_patient_portal",
    targetColumn: "isPatientPortal",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_show_on_time_line",
    targetColumn: "isShowOnTimeLine",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "med_tech_id",
    targetColumn: "medTechId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "screening_source_type_id",
    targetColumn: "screeningSourceTypeId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "service_template_id",
    targetColumn: "serviceTemplateId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "service_template_name",
    targetColumn: "serviceTemplateName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "user_logging_id",
    targetColumn: "userLoggingId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "logging_user_name",
    targetColumn: "loggingUserName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  // Field columns - Keep as text for flexibility
  {
    sourceColumn: "field1",
    targetColumn: "field1",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field2",
    targetColumn: "field2",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field3",
    targetColumn: "field3",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field4",
    targetColumn: "field4",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field5",
    targetColumn: "field5",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field6",
    targetColumn: "field6",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field7",
    targetColumn: "field7",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field8",
    targetColumn: "field8",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field9",
    targetColumn: "field9",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field10",
    targetColumn: "field10",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field11",
    targetColumn: "field11",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field12",
    targetColumn: "field12",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field13",
    targetColumn: "field13",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field14",
    targetColumn: "field14",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field15",
    targetColumn: "field15",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field16",
    targetColumn: "field16",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field17",
    targetColumn: "field17",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field18",
    targetColumn: "field18",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field19",
    targetColumn: "field19",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field20",
    targetColumn: "field20",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field21",
    targetColumn: "field21",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field22",
    targetColumn: "field22",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field23",
    targetColumn: "field23",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field24",
    targetColumn: "field24",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field25",
    targetColumn: "field25",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field26",
    targetColumn: "field26",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field27",
    targetColumn: "field27",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field28",
    targetColumn: "field28",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field29",
    targetColumn: "field29",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field30",
    targetColumn: "field30",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field31",
    targetColumn: "field31",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field32",
    targetColumn: "field32",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field33",
    targetColumn: "field33",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field34",
    targetColumn: "field34",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field35",
    targetColumn: "field35",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field36",
    targetColumn: "field36",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field37",
    targetColumn: "field37",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field38",
    targetColumn: "field38",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field39",
    targetColumn: "field39",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field40",
    targetColumn: "field40",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field41",
    targetColumn: "field41",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field42",
    targetColumn: "field42",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field43",
    targetColumn: "field43",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field44",
    targetColumn: "field44",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field45",
    targetColumn: "field45",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field46",
    targetColumn: "field46",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field47",
    targetColumn: "field47",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field48",
    targetColumn: "field48",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field49",
    targetColumn: "field49",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field50",
    targetColumn: "field50",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field51",
    targetColumn: "field51",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field52",
    targetColumn: "field52",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field53",
    targetColumn: "field53",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field54",
    targetColumn: "field54",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field55",
    targetColumn: "field55",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field56",
    targetColumn: "field56",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field57",
    targetColumn: "field57",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field58",
    targetColumn: "field58",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field59",
    targetColumn: "field59",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field60",
    targetColumn: "field60",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field61",
    targetColumn: "field61",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field62",
    targetColumn: "field62",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field63",
    targetColumn: "field63",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field64",
    targetColumn: "field64",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field65",
    targetColumn: "field65",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field66",
    targetColumn: "field66",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field67",
    targetColumn: "field67",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field68",
    targetColumn: "field68",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field69",
    targetColumn: "field69",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field70",
    targetColumn: "field70",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field71",
    targetColumn: "field71",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field72",
    targetColumn: "field72",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field73",
    targetColumn: "field73",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field74",
    targetColumn: "field74",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field75",
    targetColumn: "field75",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field76",
    targetColumn: "field76",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field77",
    targetColumn: "field77",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field78",
    targetColumn: "field78",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field79",
    targetColumn: "field79",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field80",
    targetColumn: "field80",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field81",
    targetColumn: "field81",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field82",
    targetColumn: "field82",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field83",
    targetColumn: "field83",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field84",
    targetColumn: "field84",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field85",
    targetColumn: "field85",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field86",
    targetColumn: "field86",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field87",
    targetColumn: "field87",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field88",
    targetColumn: "field88",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field89",
    targetColumn: "field89",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field90",
    targetColumn: "field90",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field91",
    targetColumn: "field91",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field92",
    targetColumn: "field92",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field93",
    targetColumn: "field93",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field94",
    targetColumn: "field94",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field95",
    targetColumn: "field95",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field96",
    targetColumn: "field96",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field97",
    targetColumn: "field97",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field98",
    targetColumn: "field98",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field99",
    targetColumn: "field99",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "field100",
    targetColumn: "field100",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "score",
    targetColumn: "score",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "screening_type_id",
    targetColumn: "screeningTypeId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_latitude",
    targetColumn: "permanentAddressLatitude",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "permanent_address_longitude",
    targetColumn: "permanentAddressLongitude",
    targetType: ColumnType.DECIMAL,
    required: false,
  },
  {
    sourceColumn: "practice_location_id",
    targetColumn: "practiceLocationId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "location_name",
    targetColumn: "locationName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "per_org_id",
    targetColumn: "perOrgId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "loaded_date_time",
    targetColumn: "loadedDateTime",
    targetType: ColumnType.TIMESTAMP,
    required: false,
  },
];
