import type { ColumnTransformation } from "../types/transformer";
import { ColumnType } from "../types/transformer";

/**
 * Patients staging transformations
 * Converts raw text columns to typed staging columns
 */
export const patientsTransformations: ColumnTransformation[] = [
  // IDs - Keep as text
  {
    sourceColumn: "patient_id",
    targetColumn: "patientId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "nhi_number",
    targetColumn: "nhiNumber",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "per_org_id",
    targetColumn: "perOrgId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "practice_id",
    targetColumn: "practiceId",
    targetType: ColumnType.TEXT,
    required: true,
  },

  // Boolean fields
  {
    sourceColumn: "is_nhi_validate",
    targetColumn: "isNhiValidate",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_alive",
    targetColumn: "isAlive",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "consented_to_share",
    targetColumn: "consentedToShare",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_portal_user",
    targetColumn: "isPortalUser",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_active",
    targetColumn: "isActive",
    targetType: ColumnType.BOOLEAN,
    required: false,
    defaultValue: true,
  },
  {
    sourceColumn: "is_deleted",
    targetColumn: "isDeleted",
    targetType: ColumnType.BOOLEAN,
    required: false,
    defaultValue: false,
  },

  // Date fields
  {
    sourceColumn: "dob",
    targetColumn: "dob",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "death_date",
    targetColumn: "deathDate",
    targetType: ColumnType.DATE,
    required: false,
  },

  // Integer fields
  {
    sourceColumn: "age",
    targetColumn: "age",
    targetType: ColumnType.INTEGER,
    required: false,
  },

  // Text fields - Personal information
  {
    sourceColumn: "title",
    targetColumn: "title",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "first_name",
    targetColumn: "firstName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "middle_name",
    targetColumn: "middleName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "family_name",
    targetColumn: "familyName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "full_name",
    targetColumn: "fullName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "preferred_name",
    targetColumn: "preferredName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "other_maiden_name",
    targetColumn: "otherMaidenName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },

  // Demographic fields
  {
    sourceColumn: "marital_status_id",
    targetColumn: "maritalStatusId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "marital_status",
    targetColumn: "maritalStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "gender_id",
    targetColumn: "genderId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "gender",
    targetColumn: "gender",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "age_type",
    targetColumn: "ageType",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "age_group",
    targetColumn: "ageGroup",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "dob_source",
    targetColumn: "dobSource",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "picture_path",
    targetColumn: "picturePath",
    targetType: ColumnType.TEXT,
    required: false,
  },

  // Contact information
  {
    sourceColumn: "cell_number",
    targetColumn: "cellNumber",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "day_phone",
    targetColumn: "dayPhone",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "night_phone",
    targetColumn: "nightPhone",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "email",
    targetColumn: "email",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.toLowerCase().trim() ?? null,
  },
  {
    sourceColumn: "secondary_email",
    targetColumn: "secondaryEmail",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.toLowerCase().trim() ?? null,
  },
  {
    sourceColumn: "preferred_contact_method",
    targetColumn: "preferredContactMethod",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "consent_text_messaging",
    targetColumn: "consentTextMessaging",
    targetType: ColumnType.TEXT,
    required: false,
  },

  // Birth information
  {
    sourceColumn: "place_of_birth",
    targetColumn: "placeOfBirth",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "country_of_birth_id",
    targetColumn: "countryOfBirthId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "country_of_birth",
    targetColumn: "countryOfBirth",
    targetType: ColumnType.TEXT,
    required: false,
  },

  // Address fields (simplified - keeping as text for now)
  {
    sourceColumn: "permanent_address_house_number",
    targetColumn: "permanentAddressHouseNumber",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_building_number",
    targetColumn: "permanentAddressBuildingNumber",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_street_number",
    targetColumn: "permanentAddressStreetNumber",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_suburb_town_id",
    targetColumn: "permanentAddressSuburbTownId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_suburb",
    targetColumn: "permanentAddressSuburb",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_city_area_id",
    targetColumn: "permanentAddressCityAreaId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_city",
    targetColumn: "permanentAddressCity",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_postal_code",
    targetColumn: "permanentAddressPostalCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_latitude",
    targetColumn: "permanentAddressLatitude",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_longitude",
    targetColumn: "permanentAddressLongitude",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_country_id",
    targetColumn: "permanentAddressCountryId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_country",
    targetColumn: "permanentAddressCountry",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address",
    targetColumn: "permanentAddress",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_dhb_code",
    targetColumn: "permanentAddressDhbCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_domicile_code",
    targetColumn: "permanentAddressDomicileCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_deprivation_quintile",
    targetColumn: "permanentAddressDeprivationQuintile",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_deprivation_decile",
    targetColumn: "permanentAddressDeprivationDecile",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_meshblock",
    targetColumn: "permanentAddressMeshblock",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_match_score",
    targetColumn: "permanentAddressMatchScore",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address_uncertainty_code",
    targetColumn: "permanentAddressUncertaintyCode",
    targetType: ColumnType.TEXT,
    required: false,
  },

  // Postal address fields
  {
    sourceColumn: "postal_address_house_number",
    targetColumn: "postalAddressHouseNumber",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_building_number",
    targetColumn: "postalAddressBuildingNumber",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_street_number",
    targetColumn: "postalAddressStreetNumber",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_suburb_town_id",
    targetColumn: "postalAddressSuburbTownId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_suburb",
    targetColumn: "postalAddressSuburb",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_city_area_id",
    targetColumn: "postalAddressCityAreaId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_city",
    targetColumn: "postalAddressCity",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_postal_code",
    targetColumn: "postalAddressPostalCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_latitude",
    targetColumn: "postalAddressLatitude",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_longitude",
    targetColumn: "postalAddressLongitude",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_country_id",
    targetColumn: "postalAddressCountryId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_country",
    targetColumn: "postalAddressCountry",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address",
    targetColumn: "postalAddress",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_dhb_code",
    targetColumn: "postalAddressDhbCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_domicile_code",
    targetColumn: "postalAddressDomicileCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_deprivation_quintile",
    targetColumn: "postalAddressDeprivationQuintile",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_deprivation_decile",
    targetColumn: "postalAddressDeprivationDecile",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_meshblock",
    targetColumn: "postalAddressMeshblock",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_match_score",
    targetColumn: "postalAddressMatchScore",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address_uncertainty_code",
    targetColumn: "postalAddressUncertaintyCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "temporary_address",
    targetColumn: "temporaryAddress",
    targetType: ColumnType.TEXT,
    required: false,
  },

  // Ethnicity fields
  {
    sourceColumn: "ethnicity_id",
    targetColumn: "ethnicityId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "ethnicity",
    targetColumn: "ethnicity",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "ethcode",
    targetColumn: "ethcode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "ethcode2",
    targetColumn: "ethcode2",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "secondary_ethnicity_id",
    targetColumn: "secondaryEthnicityId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "secondary_ethnicity",
    targetColumn: "secondaryEthnicity",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "ethcode3",
    targetColumn: "ethcode3",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "other_ethnicity_id",
    targetColumn: "otherEthnicityId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "other_ethnicity",
    targetColumn: "otherEthnicity",
    targetType: ColumnType.TEXT,
    required: false,
  },

  // Enrollment and funding fields
  {
    sourceColumn: "enrolment_id",
    targetColumn: "enrolmentId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "pho_name",
    targetColumn: "phoName",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "enrolment_expiry_date",
    targetColumn: "enrolmentExpiryDate",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "is_consent_to_share",
    targetColumn: "isConsentToShare",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_work_visa",
    targetColumn: "isWorkVisa",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "work_visa_start_date",
    targetColumn: "workVisaStartDate",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "work_visa_expiry_date",
    targetColumn: "workVisaExpiryDate",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "enrolment_quarter",
    targetColumn: "enrolmentQuarter",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "practice_location",
    targetColumn: "practiceLocation",
    targetType: ColumnType.TEXT,
    required: false,
  },

  // Additional boolean fields
  {
    sourceColumn: "is_gender_self_identified",
    targetColumn: "isGenderSelfIdentified",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_worked_visa_required",
    targetColumn: "isWorkedVisaRequired",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_insured",
    targetColumn: "isInsured",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_transfer_of_records",
    targetColumn: "isTransferOfRecords",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_health_card",
    targetColumn: "isHealthCard",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_pregnant",
    targetColumn: "isPregnant",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },

  // Additional text fields
  {
    sourceColumn: "notes",
    targetColumn: "notes",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "sex_related_gender",
    targetColumn: "sexRelatedGender",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "balance",
    targetColumn: "balance",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "med_tech_balance",
    targetColumn: "medTechBalance",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "medtech_date_lastpay",
    targetColumn: "medtechDateLastPay",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "medtech_date_laststmt",
    targetColumn: "medtechDateLastStmt",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "register_status_id",
    targetColumn: "registerStatusId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "register_status",
    targetColumn: "registerStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "med_tech_nok",
    targetColumn: "medTechNok",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "practice_name",
    targetColumn: "practiceName",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "calculated_balance",
    targetColumn: "calculatedBalance",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "last_statement_date",
    targetColumn: "lastStatementDate",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "last_invoice_date",
    targetColumn: "lastInvoiceDate",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "last_payment_date",
    targetColumn: "lastPaymentDate",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "provider_name",
    targetColumn: "providerName",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "chart_number",
    targetColumn: "chartNumber",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "extention",
    targetColumn: "extention",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "practice_remarks",
    targetColumn: "practiceRemarks",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "insured_remarks",
    targetColumn: "insuredRemarks",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "smoking_type",
    targetColumn: "smokingType",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "account_holder",
    targetColumn: "accountHolder",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "account_holder_employer",
    targetColumn: "accountHolderEmployer",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "community_service_card_no",
    targetColumn: "communityServiceCardNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "community_service_card_exipry_date",
    targetColumn: "communityServiceCardExipryDate",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "community_service_card_sighted",
    targetColumn: "communityServiceCardSighted",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "health_card_no",
    targetColumn: "healthCardNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "health_card_expiry_date",
    targetColumn: "healthCardExpiryDate",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "health_card_sighted",
    targetColumn: "healthCardSighted",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "winz",
    targetColumn: "winz",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "transferof_records_remarks",
    targetColumn: "transferofRecordsRemarks",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "enrolment_type",
    targetColumn: "enrolmentType",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "enrolment_status_id",
    targetColumn: "enrolmentStatusId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "enrolment_status",
    targetColumn: "enrolmentStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "enrolment_date",
    targetColumn: "enrolmentDate",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "enrolment_method",
    targetColumn: "enrolmentMethod",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "enrolment_verifier",
    targetColumn: "enrolmentVerifier",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "funding_status_id",
    targetColumn: "fundingStatusId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "funding_status",
    targetColumn: "fundingStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "rejection_reason",
    targetColumn: "rejectionReason",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "funding_from",
    targetColumn: "fundingFrom",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "funding_to",
    targetColumn: "fundingTo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "account_group",
    targetColumn: "accountGroup",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "gms_code",
    targetColumn: "gmsCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "residential_status",
    targetColumn: "residentialStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "is_nka",
    targetColumn: "isNka",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_high_care",
    targetColumn: "isHighCare",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "high_care_reason",
    targetColumn: "highCareReason",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "is_care_plan",
    targetColumn: "isCarePlan",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_new_registeration",
    targetColumn: "isNewRegisteration",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_opt_off",
    targetColumn: "isOptOff",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_bp_graph",
    targetColumn: "isBpGraph",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_bmi_graph",
    targetColumn: "isBmiGraph",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_inr_graph",
    targetColumn: "isInrGraph",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_hba1c_graph",
    targetColumn: "isHba1cGraph",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "asr_mark_status",
    targetColumn: "asrMarkStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "is_height_graph",
    targetColumn: "isHeightGraph",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_weight_graph",
    targetColumn: "isWeightGraph",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_hc_graph",
    targetColumn: "isHcGraph",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "nes_status",
    targetColumn: "nesStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "nes_comments",
    targetColumn: "nesComments",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "med_tech_balance_date",
    targetColumn: "medTechBalanceDate",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "is_heart_rate",
    targetColumn: "isHeartRate",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_premature",
    targetColumn: "isPremature",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "premature_week",
    targetColumn: "prematureWeek",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "patient_phoid",
    targetColumn: "patientPhoid",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "consult_updated_at",
    targetColumn: "consultUpdatedAt",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "occupation",
    targetColumn: "occupation",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "emergency_contact",
    targetColumn: "emergencyContact",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "emergency_contact_name",
    targetColumn: "emergencyContactName",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "secondary_contact",
    targetColumn: "secondaryContact",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "secondary_contact_name",
    targetColumn: "secondaryContactName",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "portal_registration_status",
    targetColumn: "portalRegistrationStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "registration_date",
    targetColumn: "registrationDate",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "med_tech_id",
    targetColumn: "medTechId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "account_holder_type_id",
    targetColumn: "accountHolderTypeId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "patient_type",
    targetColumn: "patientType",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "breast_screen_id",
    targetColumn: "breastScreenId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "breast_screen",
    targetColumn: "breastScreen",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "apply_charges",
    targetColumn: "applyCharges",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "include_in_print",
    targetColumn: "includeInPrint",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_careplus",
    targetColumn: "isCareplus",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "care_plus_start_date",
    targetColumn: "carePlusStartDate",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "care_plus_enddate",
    targetColumn: "carePlusEnddate",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "care_plus_linc_status_id",
    targetColumn: "carePlusLincStatusId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "care_plus_linc_status",
    targetColumn: "carePlusLincStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "nhi_status_id",
    targetColumn: "nhiStatusId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "nhi_status",
    targetColumn: "nhiStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "account_holder_profile_id",
    targetColumn: "accountHolderProfileId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "comunity_service_effective_date",
    targetColumn: "comunityServiceEffectiveDate",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "default_gpmc_no",
    targetColumn: "defaultGpmcNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "default_gp_name",
    targetColumn: "defaultGpName",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "default_practice_edi",
    targetColumn: "defaultPracticeEdi",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "default_practice_name",
    targetColumn: "defaultPracticeName",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "enrolment_end_date",
    targetColumn: "enrolmentEndDate",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "is_capitated",
    targetColumn: "isCapitated",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_consent_auto_reminder_text_messaging",
    targetColumn: "isConsentAutoReminderTextMessaging",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_consent_for_experience_survey",
    targetColumn: "isConsentForExperienceSurvey",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_consent_to_import_clinical_records",
    targetColumn: "isConsentToImportClinicalRecords",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_consent_to_private_email_address",
    targetColumn: "isConsentToPrivateEmailAddress",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_consent_to_share_clinical_records",
    targetColumn: "isConsentToShareClinicalRecords",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_consent_to_share_health1",
    targetColumn: "isConsentToShareHealth1",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_consent_to_share_my_record_on_sehr",
    targetColumn: "isConsentToShareMyRecordOnSehr",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_consent_to_share_pho_data_collection",
    targetColumn: "isConsentToSharePhoDataCollection",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_include_account_fee",
    targetColumn: "isIncludeAccountFee",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_include_statement_fee",
    targetColumn: "isIncludeStatementFee",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_linked_csc_exists",
    targetColumn: "isLinkedCscExists",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_test_record",
    targetColumn: "isTestRecord",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "pharmacy_id",
    targetColumn: "pharmacyId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "residential_status_id",
    targetColumn: "residentialStatusId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "visa_expiry",
    targetColumn: "visaExpiry",
    targetType: ColumnType.TEXT,
    required: false,
  },
];
