import type { ColumnTransformation } from "../types/transformer";
import { ColumnType } from "../types/transformer";

/**
 * Providers staging transformations
 * Converts raw text columns to typed staging columns
 */
export const providersTransformations: ColumnTransformation[] = [
  // IDs
  {
    sourceColumn: "provider_id",
    targetColumn: "providerId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "practice_id",
    targetColumn: "practiceId",
    targetType: ColumnType.TEXT,
    required: true,
  },
  {
    sourceColumn: "per_org_id",
    targetColumn: "perOrgId",
    targetType: ColumnType.TEXT,
    required: true,
  },

  // Professional identifiers
  {
    sourceColumn: "nhi_number",
    targetColumn: "nhiNumber",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "nzmc_no",
    targetColumn: "nzmcNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "npi_no",
    targetColumn: "npiNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "provider_code",
    targetColumn: "providerCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "accreditation_no",
    targetColumn: "accreditationNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "hpi_no",
    targetColumn: "hpiNo",
    targetType: ColumnType.TEXT,
    required: false,
  },

  // Personal details
  {
    sourceColumn: "title",
    targetColumn: "title",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "first_name",
    targetColumn: "firstName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "middle_name",
    targetColumn: "middleName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "family_name",
    targetColumn: "familyName",
    targetType: ColumnType.TEXT,
    required: true,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "full_name",
    targetColumn: "fullName",
    targetType: ColumnType.TEXT,
    required: true,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "preferred_name",
    targetColumn: "preferredName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "gender",
    targetColumn: "gender",
    targetType: ColumnType.TEXT,
    required: false,
  },

  // Dates
  {
    sourceColumn: "dob",
    targetColumn: "dob",
    targetType: ColumnType.DATE,
    required: false,
  },
  {
    sourceColumn: "death_date",
    targetColumn: "deathDate",
    targetType: ColumnType.DATE,
    required: false,
  },

  // Booleans
  {
    sourceColumn: "is_alive",
    targetColumn: "isAlive",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_active",
    targetColumn: "isActive",
    targetType: ColumnType.BOOLEAN,
    required: false,
    defaultValue: true,
  },
  {
    sourceColumn: "is_deleted",
    targetColumn: "isDeleted",
    targetType: ColumnType.BOOLEAN,
    required: false,
    defaultValue: false,
  },
  {
    sourceColumn: "is_portal_user",
    targetColumn: "isPortalUser",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_gender_self_identified",
    targetColumn: "isGenderSelfIdentified",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_worked_visa_required",
    targetColumn: "isWorkedVisaRequired",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_doctor",
    targetColumn: "isDoctor",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_invoicing_diary",
    targetColumn: "isInvoicingDiary",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_gp2gp",
    targetColumn: "isGp2Gp",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },

  // Contact information
  {
    sourceColumn: "email",
    targetColumn: "email",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.toLowerCase().trim() ?? null,
  },
  {
    sourceColumn: "cell_number",
    targetColumn: "cellNumber",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "day_phone",
    targetColumn: "dayPhone",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "night_phone",
    targetColumn: "nightPhone",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },

  // Practice relationship
  {
    sourceColumn: "practice_name",
    targetColumn: "practiceName",
    targetType: ColumnType.TEXT,
    required: false,
    transformFunction: (value) => value?.trim() ?? null,
  },
  {
    sourceColumn: "user_role",
    targetColumn: "userRole",
    targetType: ColumnType.TEXT,
    required: false,
  },

  // Additional fields (keeping as text for now)
  {
    sourceColumn: "sex_related_gender",
    targetColumn: "sexRelatedGender",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "balance",
    targetColumn: "balance",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "register_status",
    targetColumn: "registerStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "med_tech_nok",
    targetColumn: "medTechNok",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "calculated_balance",
    targetColumn: "calculatedBalance",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "permanent_address",
    targetColumn: "permanentAddress",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "deprivation_quintile",
    targetColumn: "deprivationQuintile",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "uncertainty_code",
    targetColumn: "uncertaintyCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "postal_address",
    targetColumn: "postalAddress",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "temporary_address",
    targetColumn: "temporaryAddress",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "city",
    targetColumn: "city",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "suburb",
    targetColumn: "suburb",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "portal_registration_status",
    targetColumn: "portalRegistrationStatus",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "ethnicity",
    targetColumn: "ethnicity",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "affiliation_id",
    targetColumn: "affiliationId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "affiliation",
    targetColumn: "affiliation",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "affiliation_code",
    targetColumn: "affiliationCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "hbl_mat_payee_no",
    targetColumn: "hblMatPayeeNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "hbl_mat_agree_no",
    targetColumn: "hblMatAgreeNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "hpac_mat_agree_no",
    targetColumn: "hpacMatAgreeNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "hpac_mat_agree_ver",
    targetColumn: "hpacMatAgreeVer",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "hbl_payee_no",
    targetColumn: "hblPayeeNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "hbl_gpa_agree_no",
    targetColumn: "hblGpaAgreeNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "hbl_gpa_agree_ver",
    targetColumn: "hblGpaAgreeVer",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "pho_contract_no",
    targetColumn: "phoContractNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "pho_contract_ver",
    targetColumn: "phoContractVer",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "group_id",
    targetColumn: "groupId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "group_name",
    targetColumn: "groupName",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "acc_provider_code",
    targetColumn: "accProviderCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "health_facility_no",
    targetColumn: "healthFacilityNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "unload_ref",
    targetColumn: "unloadRef",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "acc_provider_no",
    targetColumn: "accProviderNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "acc_vendor_id",
    targetColumn: "accVendorId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "pin_pan_no",
    targetColumn: "pinPanNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "member_no",
    targetColumn: "memberNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "rha_payee_no",
    targetColumn: "rhaPayeeNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "budget_no",
    targetColumn: "budgetNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "ipa",
    targetColumn: "ipa",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "registration_no",
    targetColumn: "registrationNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "lab_no",
    targetColumn: "labNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "lab_tests_dr_id",
    targetColumn: "labTestsDrId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "color_code",
    targetColumn: "colorCode",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "acc45_prefix",
    targetColumn: "acc45Prefix",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "next_acc45_no",
    targetColumn: "nextAcc45No",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "maximum_acc45_no",
    targetColumn: "maximumAcc45No",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "aitc_prefix",
    targetColumn: "aitcPrefix",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "next_aitc_no",
    targetColumn: "nextAitcNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "maximum_aitc_no",
    targetColumn: "maximumAitcNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "arc18_next_acc_form_no",
    targetColumn: "arc18NextAccFormNo",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "m45_prefix",
    targetColumn: "m45Prefix",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "next_m45_no",
    targetColumn: "nextM45No",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "maximum_m45_no",
    targetColumn: "maximumM45No",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "is_nzf_avoid",
    targetColumn: "isNzfAvoid",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_nzf_adjust",
    targetColumn: "isNzfAdjust",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_nzf_information",
    targetColumn: "isNzfInformation",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_nzf_no_action",
    targetColumn: "isNzfNoAction",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "is_nzf_monitor",
    targetColumn: "isNzfMonitor",
    targetType: ColumnType.BOOLEAN,
    required: false,
  },
  {
    sourceColumn: "generic_profile_type_id",
    targetColumn: "genericProfileTypeId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "current_appointment_id",
    targetColumn: "currentAppointmentId",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "sure_med_user_name",
    targetColumn: "sureMedUserName",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "from_date_practice",
    targetColumn: "fromDatePractice",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "apc_expiry_date",
    targetColumn: "apcExpiryDate",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "mps_expiry_date",
    targetColumn: "mpsExpiryDate",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "apc_name",
    targetColumn: "apcName",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "practice_location",
    targetColumn: "practiceLocation",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "provider_permanent_address_latitude",
    targetColumn: "providerPermanentAddressLatitude",
    targetType: ColumnType.TEXT,
    required: false,
  },
  {
    sourceColumn: "provider_permanent_address_longitude",
    targetColumn: "providerPermanentAddressLongitude",
    targetType: ColumnType.TEXT,
    required: false,
  },
];
