import {
  text,
  timestamp,
  uuid,
  boolean,
  integer,
  decimal,
  date,
  check,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createTable } from "../../../utils/create-table.js";

export const immunisationsStg = createTable("stg.immunisations_stg", {
  // Typed columns with proper constraints
  appointmentImmunisationId: text("appointment_immunisation_id").notNull(),
  patientId: text("patient_id"),
  appointmentId: text("appointment_id"),
  patientScheduleId: text("patient_schedule_id"),
  vaccineId: text("vaccine_id"),
  vaccineName: text("vaccine_name"),
  vaccineCode: text("vaccine_code"),
  dose: decimal("dose", { precision: 8, scale: 2 }),
  doseNumber: integer("dose_number"),
  administrationSiteId: text("administration_site_id"),
  administrationSite: text("administration_site"),
  routeId: text("route_id"),
  route: text("route"),
  batchNumber: text("batch_number"),
  expiryDate: date("expiry_date"),
  immunisationStatusId: text("immunisation_status_id"),
  immunisationStatus: text("immunisation_status"),
  vaccineOutcomeId: text("vaccine_outcome_id"),
  vaccineOutcome: text("vaccine_outcome"),
  isNirAck: boolean("is_nir_ack"),
  reason: text("reason"),
  providerId: text("provider_id"),
  provider: text("provider"),
  comments: text("comments"),
  administrationTime: timestamp("administration_time", {
    withTimezone: true,
  }),
  vaccineIndicationId: text("vaccine_indication_id"),
  vaccineIndication: text("vaccine_indication"),
  vaccineIndicationCode: text("vaccine_indication_code"),
  needleLength: decimal("needle_length", { precision: 5, scale: 2 }),
  hasDiluent: boolean("has_diluent"),
  diluentBatchNo: text("diluent_batch_no"),
  diluentExpiryDate: date("diluent_expiry_date"),
  isConfidential: boolean("is_confidential"),
  costingCodeId: text("costing_code_id"),
  costingCode: text("costing_code"),
  brandId: text("brand_id"),
  brand: text("brand"),
  isActive: boolean("is_active"),
  isDeleted: boolean("is_deleted"),
  insertedById: text("inserted_by_id"),
  insertedBy: text("inserted_by"),
  updatedById: text("updated_by_id"),
  updatedBy: text("updated_by"),
  insertedAt: timestamp("inserted_at", { withTimezone: true }),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
  isParked: boolean("is_parked"),
  medTechId: text("med_tech_id"),
  practiceId: text("practice_id").notNull(),
  practice: text("practice"),
  isAutoBill: boolean("is_auto_bill"),
  vaccinatorId: text("vaccinator_id"),
  vaccinator: text("vaccinator"),
  userLoggingId: text("user_logging_id"),
  loggingUserName: text("logging_user_name"),
  nirSentDate: date("nir_sent_date"),
  showOnPortal: boolean("show_on_portal"),
  vaccinatorCode: text("vaccinator_code"),
  permanentAddressLatitude: decimal("permanent_address_latitude", {
    precision: 10,
    scale: 8,
  }),
  permanentAddressLongitude: decimal("permanent_address_longitude", {
    precision: 11,
    scale: 8,
  }),
  practiceLocationId: text("practice_location_id"),
  locationName: text("location_name"),
  vaccineGroupId: text("vaccine_group_id"),
  vaccineGroup: text("vaccine_group"),
  perOrgId: text("per_org_id").notNull(),
  loadedDateTime: timestamp("loaded_date_time", { withTimezone: true }),

  // Lineage columns
  s3Bucket: text("s3_bucket").notNull(),
  s3Key: text("s3_key").notNull(),
  s3VersionId: text("s3_version_id").notNull(),
  fileHash: text("file_hash").notNull(),
  dateExtracted: text("date_extracted").notNull(),
  extractType: text("extract_type").notNull(),
  loadRunId: uuid("load_run_id").notNull(),
  loadTs: timestamp("load_ts", { withTimezone: true }).notNull().defaultNow(),
});

// Add unique constraint on natural key
export const immunisationsStgUniqueConstraint = check(
  "immunisations_stg_unique_constraint",
  sql`appointment_immunisation_id IS NOT NULL AND practice_id IS NOT NULL AND per_org_id IS NOT NULL`
);
