import {
  text,
  timestamp,
  uuid,
  boolean,
  integer,
  decimal,
  date,
  check,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createTable } from "../../../utils/create-table";

export const patientsStg = createTable("stg.patients", {
  // Typed columns with proper constraints
  patientId: text("patient_id").notNull(),
  nhiNumber: text("nhi_number"),
  isNhiValidate: boolean("is_nhi_validate"),
  title: text("title"),
  firstName: text("first_name"),
  middleName: text("middle_name"),
  familyName: text("family_name"),
  fullName: text("full_name"),
  preferredName: text("preferred_name"),
  otherMaidenName: text("other_maiden_name"),
  maritalStatusId: text("marital_status_id"),
  maritalStatus: text("marital_status"),
  genderId: text("gender_id"),
  gender: text("gender"),
  dob: date("dob"),
  age: integer("age"),
  ageType: text("age_type"),
  ageGroup: text("age_group"),
  isAlive: boolean("is_alive"),
  deathDate: date("death_date"),
  dobSource: text("dob_source"),
  picturePath: text("picture_path"),
  consentedToShare: boolean("consented_to_share"),
  placeOfBirth: text("place_of_birth"),
  countryOfBirthId: text("country_of_birth_id"),
  countryOfBirth: text("country_of_birth"),
  cellNumber: text("cell_number"),
  dayPhone: text("day_phone"),
  nightPhone: text("night_phone"),
  email: text("email"),
  secondaryEmail: text("secondary_email"),
  preferredContactMethod: text("preferred_contact_method"),
  consentTextMessaging: boolean("consent_text_messaging"),
  isPortalUser: boolean("is_portal_user"),
  isActive: boolean("is_active"),
  isDeleted: boolean("is_deleted"),
  insertedBy: text("inserted_by"),
  updatedBy: text("updated_by"),
  insertedAt: timestamp("inserted_at", { withTimezone: true }),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
  notes: text("notes"),
  isGenderSelfIdentified: boolean("is_gender_self_identified"),
  sexRelatedGender: text("sex_related_gender"),
  isWorkedVisaRequired: boolean("is_worked_visa_required"),
  balance: decimal("balance", { precision: 10, scale: 2 }),
  medTechBalance: decimal("med_tech_balance", { precision: 10, scale: 2 }),
  medTechDateLastPay: date("med_tech_date_last_pay"),
  medTechDateLastStmt: date("med_tech_date_last_stmt"),
  registerStatusId: text("register_status_id"),
  registerStatus: text("register_status"),
  medTechNok: text("med_tech_nok"),
  practiceName: text("practice_name"),
  calculatedBalance: decimal("calculated_balance", {
    precision: 10,
    scale: 2,
  }),
  lastStatementDate: date("last_statement_date"),
  lastInvoiceDate: date("last_invoice_date"),
  lastPaymentDate: date("last_payment_date"),
  providerName: text("provider_name"),
  chartNumber: text("chart_number"),
  extention: text("extention"),
  practiceRemarks: text("practice_remarks"),
  isInsured: boolean("is_insured"),
  insuredRemarks: text("insured_remarks"),
  smokingType: text("smoking_type"),
  accountHolder: text("account_holder"),
  accountHolderEmployer: text("account_holder_employer"),
  isCommunityServiceCard: boolean("is_community_service_card"),
  communityServiceCardNo: text("community_service_card_no"),
  communityServiceCardExipryDate: date("community_service_card_exipry_date"),
  communityServiceCardSighted: boolean("community_service_card_sighted"),
  isHealthCard: boolean("is_health_card"),
  healthCardNo: text("health_card_no"),
  healthCardExpiryDate: date("health_card_expiry_date"),
  healthCardSighted: boolean("health_card_sighted"),
  winz: text("winz"),
  isTransferOfRecords: boolean("is_transfer_of_records"),
  transferOfRecordsRemarks: text("transfer_of_records_remarks"),
  enrolmentType: text("enrolment_type"),
  enrolmentStatusId: text("enrolment_status_id"),
  enrolmentStatus: text("enrolment_status"),
  enrolmentDate: date("enrolment_date"),
  enrolmentMethod: text("enrolment_method"),
  enrolmentVerifier: text("enrolment_verifier"),
  fundingStatusId: text("funding_status_id"),
  fundingStatus: text("funding_status"),
  rejectionReason: text("rejection_reason"),
  fundingFrom: date("funding_from"),
  fundingTo: date("funding_to"),
  accountGroup: text("account_group"),
  gmsCode: text("gms_code"),
  residentialStatus: text("residential_status"),
  isNka: boolean("is_nka"),
  isHighCare: boolean("is_high_care"),
  highCareReason: text("high_care_reason"),
  isCarePlan: boolean("is_care_plan"),
  isNewRegisteration: boolean("is_new_registeration"),
  isOptOff: boolean("is_opt_off"),
  isBpGraph: boolean("is_bp_graph"),
  isBmiGraph: boolean("is_bmi_graph"),
  isInrGraph: boolean("is_inr_graph"),
  isHba1cGraph: boolean("is_hba1c_graph"),
  asrMarkStatus: text("asr_mark_status"),
  isHeightGraph: boolean("is_height_graph"),
  isWeightGraph: boolean("is_weight_graph"),
  isHcGraph: boolean("is_hc_graph"),
  nesStatus: text("nes_status"),
  nesComments: text("nes_comments"),
  medTechBalanceDate: date("med_tech_balance_date"),
  isHeartRate: boolean("is_heart_rate"),
  isPremature: boolean("is_premature"),
  prematureWeek: integer("premature_week"),
  patientPhoId: text("patient_pho_id"),
  consultUpdatedAt: timestamp("consult_updated_at", { withTimezone: true }),
  occupation: text("occupation"),
  emergencyContact: text("emergency_contact"),
  emergencyContactName: text("emergency_contact_name"),
  secondaryContact: text("secondary_contact"),
  secondaryContactName: text("secondary_contact_name"),
  providerId: text("provider_id"),
  practiceId: text("practice_id").notNull(),
  portalRegistrationStatus: text("portal_registration_status"),
  registrationDate: date("registration_date"),
  medTechId: text("med_tech_id"),
  permanentAddressHouseNumber: text("permanent_address_house_number"),
  permanentAddressBuildingNumber: text("permanent_address_building_number"),
  permanentAddressStreetNumber: text("permanent_address_street_number"),
  permanentAddressSuburbTownId: text("permanent_address_suburb_town_id"),
  permanentAddressSuburb: text("permanent_address_suburb"),
  permanentAddressCityAreaId: text("permanent_address_city_area_id"),
  permanentAddressCity: text("permanent_address_city"),
  permanentAddressPostalCode: text("permanent_address_postal_code"),
  permanentAddressLatitude: decimal("permanent_address_latitude", {
    precision: 10,
    scale: 8,
  }),
  permanentAddressLongitude: decimal("permanent_address_longitude", {
    precision: 11,
    scale: 8,
  }),
  permanentAddressCountryId: text("permanent_address_country_id"),
  permanentAddressCountry: text("permanent_address_country"),
  permanentAddress: text("permanent_address"),
  permanentAddressDhbCode: text("permanent_address_dhb_code"),
  permanentAddressDomicileCode: text("permanent_address_domicile_code"),
  permanentAddressDeprivationQuintile: integer(
    "permanent_address_deprivation_quintile"
  ),
  permanentAddressDeprivationDecile: integer(
    "permanent_address_deprivation_decile"
  ),
  permanentAddressMeshblock: text("permanent_address_meshblock"),
  permanentAddressMatchScore: decimal("permanent_address_match_score", {
    precision: 5,
    scale: 2,
  }),
  permanentAddressUncertaintyCode: text("permanent_address_uncertainty_code"),
  temporaryAddress: text("temporary_address"),
  postalAddressHouseNumber: text("postal_address_house_number"),
  postalAddressBuildingNumber: text("postal_address_building_number"),
  postalAddressStreetNumber: text("postal_address_street_number"),
  postalAddressSuburbTownId: text("postal_address_suburb_town_id"),
  postalAddressSuburb: text("postal_address_suburb"),
  postalAddressCityAreaId: text("postal_address_city_area_id"),
  postalAddressCity: text("postal_address_city"),
  postalAddressPostalCode: text("postal_address_postal_code"),
  postalAddressLatitude: decimal("postal_address_latitude", {
    precision: 10,
    scale: 8,
  }),
  postalAddressLongitude: decimal("postal_address_longitude", {
    precision: 11,
    scale: 8,
  }),
  postalAddressCountryId: text("postal_address_country_id"),
  postalAddressCountry: text("postal_address_country"),
  postalAddress: text("postal_address"),
  postalAddressDhbCode: text("postal_address_dhb_code"),
  postalAddressDomicileCode: text("postal_address_domicile_code"),
  postalAddressDeprivationQuintile: integer(
    "postal_address_deprivation_quintile"
  ),
  postalAddressDeprivationDecile: integer("postal_address_deprivation_decile"),
  postalAddressMeshblock: text("postal_address_meshblock"),
  postalAddressMatchScore: decimal("postal_address_match_score", {
    precision: 5,
    scale: 2,
  }),
  postalAddressUncertaintyCode: text("postal_address_uncertainty_code"),
  ethnicityId: text("ethnicity_id"),
  ethnicity: text("ethnicity"),
  ethcode: text("ethcode"),
  ethcode2: text("ethcode2"),
  secondaryEthnicityId: text("secondary_ethnicity_id"),
  secondaryEthnicity: text("secondary_ethnicity"),
  ethcode3: text("ethcode3"),
  otherEthnicityId: text("other_ethnicity_id"),
  otherEthnicity: text("other_ethnicity"),
  enrolmentId: text("enrolment_id"),
  phoName: text("pho_name"),
  enrolmentExpiryDate: date("enrolment_expiry_date"),
  isConsentToShare: boolean("is_consent_to_share"),
  isWorkVisa: boolean("is_work_visa"),
  workVisaStartDate: date("work_visa_start_date"),
  workVisaExpiryDate: date("work_visa_expiry_date"),
  enrolmentQuarter: text("enrolment_quarter"),
  practiceLocation: text("practice_location"),
  accountHolderTypeId: text("account_holder_type_id"),
  patientType: text("patient_type"),
  breastScreenId: text("breast_screen_id"),
  breastScreen: text("breast_screen"),
  isPregnant: boolean("is_pregnant"),
  applyCharges: boolean("apply_charges"),
  includeInPrint: boolean("include_in_print"),
  isCareplus: boolean("is_careplus"),
  carePlusStartDate: date("care_plus_start_date"),
  carePlusEnddate: date("care_plus_enddate"),
  carePlusLincStatusId: text("care_plus_linc_status_id"),
  carePlusLincStatus: text("care_plus_linc_status"),
  nhiStatusId: text("nhi_status_id"),
  nhiStatus: text("nhi_status"),
  perOrgId: text("per_org_id").notNull(),
  loadedDateTime: timestamp("loaded_date_time", { withTimezone: true }),

  // Lineage columns
  s3Bucket: text("s3_bucket").notNull(),
  s3Key: text("s3_key").notNull(),
  s3VersionId: text("s3_version_id").notNull(),
  fileHash: text("file_hash").notNull(),
  dateExtracted: text("date_extracted").notNull(),
  extractType: text("extract_type").notNull(),
  loadRunId: uuid("load_run_id").notNull(),
  loadTs: timestamp("load_ts", { withTimezone: true }).notNull().defaultNow(),
});

// Unique constraint on natural key - proper implementation
export const patientsStgUniqueConstraint = uniqueIndex(
  "patients_stg_natural_key_idx"
).on(patientsStg.patientId, patientsStg.practiceId, patientsStg.perOrgId);
